// @Prolog: #include "stdinc.h"
// @Prolog: #include "DCPlusPlus.h"
// @Prolog: #include "ResourceManager.h"
// @Strings: std::string dcpp::ResourceManager::strings[]
// @Names: std::string dcpp::ResourceManager::names[]

enum Strings { // @DontAdd
	AAIRDCPP_LANGUAGE_FILE, // "EN_Example.xml"
	AAIRDCPP_LANGUAGE_VERSION, // "1.00"
	ACTIVE, // "Active"
	ACTIVE_SEARCH_STRING, // "Enabled / Search String"
	ADD, // "&Add"
	ADD_AS_SOURCE, // "Add as source"
	ADD_FINISHED_INSTANTLY, // "Add finished files to share instantly (if shared)"
	ADD_TO_FAVORITES, // "Add To Favorites"
	ADD_TO_QUEUE, // "Add to Queue"
	ADDED, // "Added"
	ADL_SEARCH, // "Automatic Directory Listing Search"
	ADLS_DESTINATION, // "Destination Directory"
	ADLS_DISCARD, // "Discard"
	ADLS_DOWNLOAD, // "Download Matches"
	ADLS_ENABLED, // "Enabled"
	ADLS_FULL_PATH, // "Full Path"
	ADLS_PROPERTIES, // "ADLSearch Properties"
	ADLS_SEARCH_STRING, // "Search String"
	ADLS_SIZE_MAX, // "Max FileSize"
	ADLS_SIZE_MIN, // "Min FileSize"
	ADLS_TYPE, // "Search Type"
	ADLS_UNITS, // "Size Type"
	ALL, // "All"
	ALL_3_USERS_OFFLINE, // "All 3 users offline"
	ALL_4_USERS_OFFLINE, // "All 4 users offline"
	ALL_DOWNLOAD_SLOTS_TAKEN, // "All download slots taken"
	ALL_FILE_SLOTS_TAKEN, // "All file slots taken"
	ALL_USERS_OFFLINE, // "All %d users offline"
	ALTERNATES_SEND, // "Searching TTH alternates for: "
	ANTI_PASSIVE_SEARCH, // "-- WARNING --\r\n-- You are in active mode, but have activated passive search. --\r\n-- Don't use passive search if you have search results without this option --\r\n-- because you don't get search result from passive clients !!! --\r\n-- Turn it off in settings => AirDC++ => Always use Passive Mode for Search --\r\n"
	ALLOW_NAT_TRAVERSAL, // "Allow NAT Traversal for connections with passive users"
	ANY, // "Any"
	AT_LEAST, // "At least"
	AT_MOST, // "At most"
	AUDIO, // "Audio"
	AUTO, // "Auto"
	AUTO_CONNECT, // "Auto connect / Name"
	AUTO_GRANT, // "Auto grant slot / Nick"
	AUTOMATIC, // "Automatic"
	AVERAGE, // "Average/s: "
	AVERAGE_UPLOAD, // "Upload Speed"
	AWAY, // "AWAY"
	AWAY_MODE_OFF, // "Away mode off"
	AWAY_MODE_ON, // "Away mode on: "
	B, // "B"
	BALLOON_POPUPS, // "Popups"
	BITZI_LOOKUP, // "Bitzi Lookup"
	BLOCK_FINISHED, // "Segment Block Finished, waiting..."
	BOTH_USERS_OFFLINE, // "Both users offline"
	BROWSE, // "Browse..."
	BROWSE_ACCEL, // "&Browse..."
	BROWSE_FILE_LIST, // "Browse file list"
	BUMPED, // "Bumped"
	CANCEL, // "Cancel"
	CERTIFICATE_GENERATED, // "Generated new TLS certificate"
	CERTIFICATE_NOT_TRUSTED, // "Certificate not trusted"
	CERTIFICATE_GENERATION_FAILED, // "TLS disabled, failed to generate certificate:"
	CID, // "CID"
	CIPHER, // "Cipher"
	CLEAR, // "Clear chat"
	CLIENTID, // "Client"
	CLOSE, // "Close"
	CLOSE_CONNECTION, // "Close connection"
	COLLAPSE_ALL, // "Collapse All"
	COLOR_OP, // "User is OP"
	COLOR_PASIVE, // "Passive user"
	COMMAND_TOO_LONG, // "Maximum command length exceeded"
	COMMENT, // "Comment"
	COMPRESSED, // "Compressed"
	COMPRESSION_ERROR, // "Error during compression"
	CONFIGURE, // "&Configure"
	CONFIGURED_HUB_LISTS, // "Configured Public Hub Lists"
	CONNECT, // "&Connect"
	CONNECT_ALL, // "Connect to all users"
	CONNECT_FAVUSER_HUB, // "Connect to hub"
	CONNECTED, // "Connected"
	CONNECTING, // "Connecting..."
	CONNECTING_FORCED, // "Connecting (forced)..."
	CONNECTING_TO, // "Connecting to "
	CONNECTING_TO_SERVER, // "Connecting to server"
	CONNECTION, // "Connection"
	CONNECTION_CLOSED, // "Connection closed"
	CONNECTION_DETECTION, // "Enable automatic incoming connection type detection"
	CONNECTION_ERROR, // "Connection error"
	CONNECTION_TIMEOUT, // "Connection timeout"
	CONTINUE_SEARCH, // "Continue Search"
	COPY, // "Copy"
	COPY_ALL, // "Copy All"
	COPY_DESCRIPTION, // "Copy description"
	COPY_EMAIL_ADDRESS, // "Copy email address"
	COPY_EXACT_SHARE, // "Copy Exact Share"
	COPY_HUB, // "Copy address to clipboard"
	COPY_IP, // "Copy IP"
	COPY_LINE, // "Copy actual line"
	COPY_MAGNET_LINK, // "Copy magnet link to clipboard"
	COPY_NICK, // "Copy nick"
	COPY_NICK_IP, // "Copy Nick+IP"
	COPY_TAG, // "Copy TAG"
	COPY_URL, // "Copy URL"
	CORAL, // "Use Coral network when downloading hub lists (improves reliability)"
	CORRUPTION_DETECTED, // "Corruption detected for TTH: %s, at position %d"
	COULD_NOT_OPEN_TARGET_FILE, // "Could not open target file: "
	COUNT, // "Count"
	COUNTRY, // "Country"
	CREATING_HASH, // "Hashing"
	CURRENT_VERSION, // "Current version"
	CURRENT_LANGUAGE, // "Current language"
	DATA_RETRIEVED, // "Data retrieved"
	DECOMPRESSION_ERROR, // "Error during decompression"
	DEFAULT, // "Default"
	DESCRIPTION, // "Description"
	DESTINATION, // "Destination"
	DIRECTORY, // "Directory"
	DIRECTORY_ADD_ERROR, // "Directory or directory name already exists"
	DISABLE_SOUNDS, // "Disable sounds"
	DISABLED, // "Disabled"
	DISCONNECT_ALL, // "Disconnect all users"
	DISCONNECT_USER, // "Disconnect user(s)"
	DISCONNECTED, // "Disconnected"
	DISCONNECTED_USER, // "Disconnected user leaving the hub: "
	DOCUMENT, // "Document"
	DONE, // "Done"
	DONT_ADD_SEGMENT_TEXT, // "Don't begin new segment if overall file speed is over"
	DONT_REMOVE_SLASH_PASSWORD, // "Don't remove /password before your password"
	DONT_SHARE_TEMP_DIRECTORY, // "The temporary download directory cannot be shared"
	DOWNLOAD, // "Download"
	DOWNLOAD_FAILED, // "Download failed: "
	DOWNLOAD_FINISHED_IDLE, // "Download finished, idle..."
	DOWNLOAD_QUEUE, // "Download queue"
	DOWNLOAD_STARTING, // "Download starting..."
	DOWNLOAD_TO, // "Download to..."
	DOWNLOAD_WHOLE_DIR, // "Download whole directory"
	DOWNLOAD_WHOLE_DIR_TO, // "Download whole directory to..."
	DOWNLOAD_WITH_PRIORITY, // "Download with priority..."
	DOWNLOADED, // "Downloaded"
	DOWNLOADED_BYTES, // "Downloaded %s (%.01f%%) in %s"
	DOWNLOADED_FROM, // " downloaded from "
	DOWNLOADED_PARTS, // "Downloaded parts"
	DOWNLOADING, // "Downloading..."
	DOWNLOADING_HUB_LIST, // "Downloading public hub list..."
	DOWNLOADING_LIST, // "Downloading list..."
	DOWNLOADS_RUNNING, // "Downloads running, please disconnect them"
	DUPLICATE_SOURCE, // "Duplicate source"
	EB, // "EiB"
	EDIT_ACCEL, // "&Edit"
	EMAIL, // "E-Mail"
	ENABLE_MULTI_SOURCE, // "Enable segmented downloads"
	ENTER_NICK, // "Please enter a nickname in the settings dialog!"
	ENTER_PASSWORD, // "Please enter a password"
	ENTER_SEARCH_STRING, // "Enter search string"
	ERROR_CREATING_HASH_DATA_FILE, // "Error creating hash data file: "
	ERROR_CREATING_REGISTRY_KEY_ADC, // "Error creating adc registry key"
	ERROR_CREATING_REGISTRY_KEY_DCHUB, // "Error creating dchub registry key"
	ERROR_CREATING_REGISTRY_KEY_MAGNET, // "Error creating magnet registry key"
	ERROR_HASHING, // "Error hashing "
	ERROR_SAVING_HASH, // "Error saving hash data: "
	ERRORS, // "Errors"
	EXACT_SHARED, // "Exact Share"
	EXACT_SIZE, // "Exact size"
	EXECUTABLE, // "Executable"
	EXPAND_ALL, // "Expand All"
	EXPANDED_RESULTS, // "Expand search results"
	EXTRA_HUB_SLOTS, // "Slot ratio"
	EXTRA_SLOTS_SET, // "Extra slots set"
	FAILED_TO_SHUTDOWN, // "Failed to shutdown!"
	FAILED_TO_LOAD_CERTIFICATE, // "Failed to load certificate file"
	FAILED_TO_LOAD_PRIVATE_KEY, // "Failed to load private key"
	FAST_HASH, // "Use fast hashing method (disable if you have problems with hashing)"
	FAV_JOIN_SHOWING_OFF, // "Join/part of favorite users showing off"
	FAV_JOIN_SHOWING_ON, // "Join/part of favorite users showing on"
	FAVORITE_DIR_NAME, // "Favorite name"
	FAVORITE_DIR_NAME_LONG, // "Under what name you see the directory"
	FAVORITE_HUB_ADDED, // "Favorite hub added"
	FAVORITE_HUB_ALREADY_EXISTS, // "Hub already exists as a favorite"
	FAVORITE_HUB_DOES_NOT_EXIST, // "This hub is not a favorite hub"
	FAVORITE_HUB_IDENTITY, // "Identification (leave blank for defaults)"
	FAVORITE_HUB_PROPERTIES, // "Favorite Hub Properties"
	FAVORITE_HUB_CONNECTION, // "Connection"
	FAVORITE_HUB_REMOVED, // "Favorite hub removed"
	FAVORITE_HUBS, // "Favorite Hubs"
	FAVORITE_USER_ADDED, // "Favorite user added"
	FAVORITE_USERS, // "Favorite Users"
	FAVUSER_ONLINE, // "Favorite user online"
	FILE, // "File"
	FILE_ALREADY_FINISHED, // "File is already finished"
	FILE_LIST, // "file list"
	FILE_LIST_DIFF, // "Subtract list"
	FILE_LIST_REFRESH_FAILED, // "File list refresh failed: "
	FILE_LIST_REFRESH_FINISHED, // "File list refresh finished"
	FILE_LIST_REFRESH_IN_PROGRESS, // "File list refresh in progress, please wait for it to finish before trying to refresh again"
	FILE_LIST_REFRESH_INITIATED, // "File list refresh initiated"
	FILE_NOT_AVAILABLE, // "File not available"
	FILE_TYPE, // "File type"
	FILE_WITH_DIFFERENT_SIZE, // "A file with a different size already exists in the queue"
	FILE_WITH_DIFFERENT_TTH, // "A file with diffent tth root already exists in the queue"
	FILENAME, // "Filename"
	FILES, // "Files"
	FILES_LEFT, // "files left"
	FILES_PER_HOUR, // "files/h"
	FILTER, // "F&ilter"
	FILTERED, // "Filtered"
	FIND, // "Find"
	FINISHED_DOWNLOAD, // "Download finished: %s"
	FINISHED_DOWNLOADS, // "Finished Downloads"
	FINISHED_UPLOAD, // "Upload finished: %s To: %s"
	FINISHED_UPLOADS, // "Finished Uploads"
	FOLDER, // "Folder"
	FORBIDDEN, // "Forbidden"
	FORBIDDEN_DOLLAR_FILE, // "File with '$' cannot be downloaded and will not be shared: "
	FORCE_ATTEMPT, // "Force attempt"
	GiB, // "GiB"
	GENERATE_CERTIFICATES, // "Generate certificates"
	GET_FILE_LIST, // "Get file list"
	GO_TO_DIRECTORY, // "Go to directory"
	GRANT_EXTRA_SLOT, // "Grant extra slot (10 min)"
	GRANT_EXTRA_SLOT_DAY, // "Grant extra slot (day)"
	GRANT_EXTRA_SLOT_HOUR, // "Grant extra slot (hour)"
	GRANT_EXTRA_SLOT_WEEK, // "Grant extra slot (week)"
	GRANT_SLOTS_MENU, // "Extra Slots"
	GROUP_SEARCH_RESULTS, // "Group search results by TTH"
	HASH_DATABASE, // "Hash database"
	HASH_PROGRESS, // "Creating file index..."
	HASH_PROGRESS_BACKGROUND, // "Run in background"
	HASH_PROGRESS_STATS, // "Statistics"
	HASH_PROGRESS_TEXT, // "Please wait while AirDC++ indexes your files (they won't be shared until they've been indexed)..."
	HASH_READ_FAILED, // "Unable to read hash data file"
	HASH_REBUILT, // "Hash database rebuilt"
	HASHING_FAILED, // "Hashing failed: "
	HASHING_FINISHED, // "Finished hashing: "
	HIBERNATE, // "Hibernate"
	HIGH, // "High"
	HIGHEST, // "Highest"
	HISTORY, // "History"
	HIT_COUNT, // "Hits"
	HIT_RATIO, // "Hit Ratio: "
	HITS, // "Hits: "
	HUB, // "Hub"
	HUB_ADDRESS, // "Address"
	HUB_CONNECTED, // "Hub connected"
	HUB_DISCONNECTED, // "Hub disconnected"
	HUB_LIST, // "Hublist"
	HUB_LIST_DOWNLOADED, // "Hub list downloaded..."
	HUB_LIST_EDIT, // "Edit the hublist"
	HUB_LIST_LOADED_FROM_CACHE, // "Hub list loaded from cache..."
	HUB_NAME, // "Name"
	HUB_SEGMENTS, // "Hub / Segments"
	HUB_TOPIC, // "Hub Topic :"
	HUB_USERS, // "Users"
	HUBLIST_CACHE_CORRUPTED, // "Cached hub list is corrupted or unsupported..."
	HUBLIST_DOWNLOAD_CORRUPTED, // "Downloaded hub list is corrupted or unsupported..."
	HUBS, // "Hubs"
	CHATDBLCLICKACTION, // "Chat double click on user action"
	CHECK_0BYTE_SHARE, // "zero bytes real size"
	CHECK_FORBIDDEN, // "Shared forbidden file : %s"
	CHECK_INFLATED, // "filelist was inflated %s times"
	CHOOSE_FOLDER, // "Choose folder"
	IGNORE_TTH_SEARCHES, // "Ignore TTH searches"
	IGNORE_USER, // "Ignore User"
	IGNORED_MESSAGE, // "Ignored message: "
	INCOMPLETE_FAV_HUB, // "Hub address cannot be empty."
	INTEGRITY_CHECK, // "Integrity check: %s (%s)"
	INVALID_LISTNAME, // "Invalid file list name"
	INVALID_NUMBER_OF_SLOTS, // "Invalid number of slots"
	INVALID_SIZE, // "Invalid size"
	INVALID_TARGET_FILE, // "Invalid target file (missing directory, check default download directory setting)"
	INVALID_TREE, // "Full tree does not match TTH root"
	IP, // "Ip: "
	IP_BARE, // "Ip"
	ITEMS, // "Items"
	JOIN_SHOWING_OFF, // "Join/part showing off"
	JOIN_SHOWING_ON, // "Join/part showing on"
	JOINS, // "Joins: "
	KiB, // "KiB"
	KBPS, // "kB/s"
	KEEP_FINISHED_FILES, // "Keep finished files in the queue"
	KICK_USER, // "Kick user(s)"
	KICK_USER_FILE, // "Kick user(s) with filename"
	LARGER_TARGET_FILE_EXISTS, // "A file of equal or larger size already exists at the target location"
	LAST_HUB, // "Hub (last seen on if offline)"
	LAST_CHANGE, // "Last change: "
	LAST_SEEN, // "Time last seen"
	LATEST_VERSION, // "Latest version"
	LANGDOWNLOAD, // "Download Language"
	LEFT, // "left"
	LEFT_COLOR, // "Left color"
	LIB_CRASH, // "Application ""%s"" caused an unhandled exception in AirDC++. Please uninstall it, upgrade it or use an alternate product."
	LIMIT, // "Upload Limit"
	LISTENER_FAILED, // "Listening socket failed (you need to restart AirDC++): "
	LOADED_FILE_LIST, // "File list loaded."
	LOADING, // "Loading AirDC++, please wait..."
	LOADING_FILE_LIST, // "Loading file list, this may take a while if the list is large."
	LOCK, // "Lock"
	LOG_OFF, // "Log off"
	LOW, // "Low"
	LOWEST, // "Lowest"
	PREVIEW_NAME, // "Name:"
	PREVIEW_APPLICATION, // "Application:"
	PREVIEW_ARGUMENTS, // "Arguments: (%[file] %[dir] available)"
	PREVIEW_EXTENSION, // "Apply to Extensions: (avi;mov;divx)"
	MAGNET_ASK, // "Ask for Magnet action"
	MAGNET_DLG_FILE, // "Filename:"
	MAGNET_DLG_HASH, // "File Hash:"
	MAGNET_DLG_NOTHING, // "Do nothing"
	MAGNET_DLG_QUEUE, // "Add this file to your download queue"
	MAGNET_DLG_REMEMBER, // "Do the same action next time without asking"
	MAGNET_DLG_SEARCH, // "Start a search for this file"
	MAGNET_DLG_SIZE, // "File Size:"
	MAGNET_DLG_TEXT_BAD, // "A MAGNET link was given to AirDC++, but it didn't contain a valid file hash for use on the Direct Connect network.  No action will be taken."
	MAGNET_DLG_TEXT_GOOD, // "AirDC++ has detected a MAGNET link with a file hash that can be searched for on the Direct Connect network.  What would you like to do?"
	MAGNET_DLG_TITLE, // "MAGNET Link detected"
	MAGNET_HANDLER_DESC, // "Download files from the Direct Connect network"
	MAGNET_HANDLER_ROOT, // "AirDC++"
	MAGNET_SHELL_DESC, // "URL:MAGNET URI"
	MANAGE_GROUPS, // "Manage Groups"
	MATCH_QUEUE, // "Match queue"
	MATCHED_FILES, // "Matched %d file(s)"
	MAX_HUBS, // "Max Hubs"
	MAX_SEGMENTS_NUMBER, // "Max number of segments"
	MAX_SIZE, // "Max Size"
	MAX_USERS, // "Max Users"
	MAXHUBS, // "Max hubs"
	MAXUSERS, // "Max users"
	MiB, // "MiB"
	MBITSPS, // "MBits/s"
	MBPS, // "MB/s"
	MENU_ABOUT, // "About AirDC++"
	MENU_ADL_SEARCH, // "ADL Search"
	MENU_ARRANGE, // "Arrange icons"
	MENU_CASCADE, // "Cascade"
	MENU_CDMDEBUG_MESSAGES, // "CDM Debug Messages"
	MENU_CLOSE_ALL_DIR_LIST, // "Close all file list windows"
	MENU_CLOSE_ALL_OFFLINE_PM, // "Close all offline PM windows"
	MENU_CLOSE_ALL_PM, // "Close all PM windows"
	MENU_CLOSE_ALL_SEARCHFRAME, // "Close all search windows"
	MENU_CLOSE_DISCONNECTED, // "Close disconnected"
	MENU_DISCUSS, // "AirDC++ Discussion forum"
	MENU_DONATE, // "Donate"
	MENU_DOWNLOAD_QUEUE, // "&Download Queue\tCtrl+D"
	MENU_EXIT, // "E&xit"
	MENU_FAQ, // "Frequently asked questions"
	MENU_FAVORITE_HUBS, // "&Favorite Hubs\tCtrl+F"
	MENU_FAVORITE_USERS, // "Favorite &Users\tCtrl+U"
	MENU_FILE, // "&File"
	MENU_FILE_RECENT_HUBS, // "&Recent Hubs"
	MENU_FOLLOW_REDIRECT, // "Follow last redirec&t\tCtrl+T"
	MENU_HASH_PROGRESS, // "Indexing progress"
	MENU_HELP, // "&Help"
	MENU_HELP_GEOIPFILE, // "GeoIP database update"
	MENU_HELP_TRANSLATIONS, // "Translations"
	MENU_HOMEPAGE, // "AirDC++ Homepage"
	MENU_HORIZONTAL_TILE, // "Horizontal Tile"
	MENU_MINIMIZE_ALL, // "Minimize &All"
	MENU_NETWORK_STATISTICS, // "Network Statistics"
	MENU_NOTEPAD, // "&Notepad\tCtrl+N"
	MENU_OPEN_DOWNLOADS_DIR, // "Open downloads directory"
	MENU_OPEN_FILE_LIST, // "Open file list...\tCtrl+L"
	MENU_OPEN_MATCH_ALL, // "Match downloaded lists"
	MENU_OPEN_OWN_LIST, // "Open own list"
	MENU_PUBLIC_HUBS, // "&Public Hubs\tCtrl+P"
	MENU_QUICK_CONNECT, // "&Quick Connect ...\tCtrl+Q"
	MENU_RECONNECT, // "&Reconnect\tCtrl+R"
	MENU_REFRESH_FILE_LIST, // "Refresh file list\tCtrl+E"
	MENU_RESTORE_ALL, // "Restore All"
	MENU_SEARCH, // "&Search\tCtrl+S"
	MENU_SEARCH_SPY, // "Search spy"
	MENU_SETTINGS, // "Settings..."
	MENU_SHOW, // "Show"
	MENU_STATUS_BAR, // "&Status bar\tCtrl+2"
	MENU_TOOLBAR, // "&Toolbar\tCtrl+1"
	MENU_TRANSFER_VIEW, // "T&ransfers\tCtrl+3"
	MENU_TRANSFERS, // "&Transfers"
	MENU_TTH, // "Get TTH for file..."
	MENU_VERTICAL_TILE, // "Vertical Tile"
	MENU_VIEW, // "&View"
	MENU_WINDOW, // "&Window"
	MENUBAR, // "Menu bar"
	MIN_SHARE, // "Min Share"
	MIN_SLOTS, // "Min Slots"
	MINIMUM_SEARCH_INTERVAL, // "Minimum search interval"
	MINSHARE, // "Min share"
	MINSLOTS, // "Min slots"
	MINUTES, // "Minutes"
	MODE, // "Mode"
	MOVE, // "Move/Rename"
	MOVE_DOWN, // "Move &Down"
	MOVE_UP, // "Move &Up"
	MYNICK_IN_CHAT, // "My nick in mainchat"
	NETWORK_STATISTICS, // "Network Statistics"
	NEW, // "&New..."
	NEW_DISCONNECT, // "Remove user from queue, if speed is below"
	NEXT, // "Next"
	NICK, // "Nick"
	NICK_TAKEN, // "Your nick was already taken, please change to something else!"
	NICK_UNKNOWN, // " (Nick unknown)"
	NO, // "No"
	NO_CERTIFICATE_FILE_SET, // "TLS disabled, no certificate file set"
	NO_DIRECTORY_SPECIFIED, // "No directory specified"
	NO_DOWNLOADS_FROM_SELF, // "You're trying to download from yourself!"
	NO_ERRORS, // "No errors"
	NO_FREE_BLOCK, // "No free block"
	NO_FULL_TREE, // "No full tree available"
	NO_LOG_FOR_HUB, // "Hub log not exist"
	NO_LOG_FOR_USER, // "User log not exist"
	NO_MATCHES, // "No matches"
	NO_NEEDED_PART, // "No needed part"
	NO_SLOTS_AVAILABLE, // "No slots available"
	NO_USERS, // "No users"
	NO_USERS_TO_DOWNLOAD_FROM, // "No users to download from"
	NONE, // "None"
	NORMAL, // "Normal"
	NOT_LISTENING, // "Not listening for connections - please restart AirDC++"
	NOTEPAD, // "Notepad"
	NUMBER_OF_SEGMENTS, // "segment(s)"
	OFFLINE, // "Offline"
	OK, // "OK"
	ONLINE, // "Online"
	ONLY_FREE_SLOTS, // "Only users with free slots"
	ONLY_TTH, // "Only results with TTH root"
	ONLY_WHERE_OP, // "Only where I'm op"
	OPEN, // "Open"
	OPEN_DOWNLOAD_PAGE, // "Open download page?"
	OPEN_FOLDER, // "Open folder"
	OPEN_HUB_LOG, // "Open hub log"
	OPEN_USER_LOG, // "Open user log"
	OVERLAP_CHUNKS, // "Overlap slow chunks by faster user when file is going to be finished"
	OVERLAPPED_SLOW_SEGMENT, // "Overlapped by faster user"
	OWN_CERTIFICATE_FILE, // "Own certificate file"
	PARTS, // "Parts: "
	PARAM_EXISTS, // "Param with same name already exists!"
	PASSIVE_USER, // "Passive user"
	PASSWORD, // "Password"
	PATH, // "Path"
	PAUSE_SEARCH, // "Pause Search"
	PAUSED, // "Paused"
	PiB, // "PiB"
	PICTURE, // "Picture"
	PLAY, // "Play"
	POPUP_DOWNLOAD_FAILED, // "Show popup on download failed"
	POPUP_DOWNLOAD_FINISHED, // "Show popup on download finished"
	POPUP_DOWNLOAD_START, // "Show popup on download begins"
	POPUP_FAVORITE_CONNECTED, // "Show popup on favorite user connected"
	POPUP_HUB_CONNECTED, // "Show popup on hub connected"
	POPUP_HUB_DISCONNECTED, // "Show popup on hub disconnected"
	POPUP_NEW_PM, // "Show popup on new private message"
	POPUP_PM, // "Show popup on private message"
	POPUP_TYPE, // "Popup type"
	POPUP_BALOON, // "Balloon popup"
	POPUP_CUSTOM, // "Custom popup"
	POPUP_SPLASH, // "Splash popup"
	POPUP_WINDOW, // "Window popup"
	POPUP_UPLOAD_FINISHED, // "Show popup on upload finished"
	PORT, // "Port: "
	POWER_OFF, // "Power off"
	PRESS_FOLLOW, // "Press the follow redirect button to connect to "
	PREVIEW_MENU, // "Preview"
	PREVIOUS_FOLDERS, // "Previous folders"
	PRIORITY, // "Priority"
	PRIVATE_KEY_FILE, // "Private key file"
	PRIVATE_MESSAGE, // "Private message"
	PRIVATE_MESSAGE_FROM, // "Private message from "
	PROGRESS_BACK, // "Transfer progressbar - background"
	PROGRESS_COMPRESS, // "Transfer progressbar - decompressed part"
	PROGRESS_DONE, // "Queue progressbar - done chunks"
	PROGRESS_DOWNLOADED, // "Queue progressbar - downloaded bytes"
	PROGRESS_RUNNING, // "Queue progressbar - running chunks"
	PROGRESS_SEGMENT, // "Transfer progressbar - actual segment"
	PROGRESS_VERIFIED, // "Queue progressbar - verified chunks"
	PROGRESSBAR_ODC_STYLE, // "Use oDC style of progressbar in Transfers"
	PROPERTIES, // "&Properties"
	PUBLIC_HUBS, // "Public Hubs"
	PURGE, // "Purge"
	REGEXP_TESTER, // "RegExp Tester"
	REGEXP_MATCH, // "It's a match!"
	REGEXP_MISMATCH, // "It's not a match."
	REGEXP_INVALID, // "Invalid RegExp!"
	REGEXP, // "RegExp"
	QUEUED, // "Queued: "
	QUICK_CONNECT, // "Quick Connect"
	RATING, // "Rating"
	RATIO, // "Ratio"
	READD_SOURCE, // "Readd source"
	REALLY_EXIT, // "Really exit?"
	REALLY_REMOVE, // "Really remove?"
	REASON, // "Reason"
	REBOOT, // "Reboot"
	RECENT_HUBS, // "Recent Hubs"
	RECHECK_FILE, // "Recheck integrity"
	REDIRECT_ALREADY_CONNECTED, // "Redirect request received to a hub that's already connected"
	REDIRECT_USER, // "Redirect user(s)"
	REFRESH, // "&Refresh"
	REFRESH_USER_LIST, // "Refresh user list"
	RELIABILITY, // "Reliability"
	REQUESTING, // "Requesting"
	REQUESTING_LIST, // "Requesting file list"
	REMOVE, // "&Remove"
	REMOVE_ALL, // "Remove all"
	REMOVE_EXTRA_SLOT, // "Remove extra slot"
	REMOVE_FROM_ALL, // "Remove user from queue"
	REMOVE_OFFLINE, // "Remove offline users"
	REMOVE_SOURCE, // "Remove source"
	RENAMED_TO, // " renamed to "
	REPORT, // "Report user"
	REPORT_ALTERNATES, // "Show auto search for alternates in System Log"
	RESUME, // "Resume"
	RETRIEVING_DATA, // "Retrieving data"
	RIGHT_COLOR, // "Right color"
	RUNNING, // "Running..."
	SEARCH, // "Search"
	SEARCH_FOR, // "Search for"
	SEARCH_FOR_ALTERNATES, // "Search for alternates"
	SEARCH_FOR_FILE, // "Search for file"
	SEARCH_IN_RESULTS, // "Search in results"
	SEARCH_OPTIONS, // "Search options"
	SEARCH_SPAM_FROM, // "Search spam detected from "
	SEARCH_SPY, // "Search Spy"
	SEARCH_STRING, // "Search String"
	SEARCHING_FOR, // "Searching for "
	SECONDS, // "Seconds"
	SEEK_BEYOND_END, // "Request to seek beyond the end of data"
	SEGMENT, // "Segment"
	SEGMENTS, // "Segments"
	SELECT_ALL, // "Select all"
	SELECT_USER_LIST, // "Select user in list"
	SEND_PRIVATE_MESSAGE, // "Send private message"
	SEND_PUBLIC_MESSAGE, // "Send public message"
	SEPARATOR, // "Separator"
	SERVER, // "Server"
	SET_PRIORITY, // "Set priority"
	SETCZDC_BACK_COLOR, // "Back color"
	SETCZDC_BLACK_WHITE, // "Black & white"
	SETCZDC_CZCHARS_DISABLE, // "Remove diacritic marks from Czech chars"
	SETCZDC_DEFAULT_STYLE, // "Default style"
	SETCZDC_DISCONNECTING_ENABLE, // "Enable slow downloads disconnecting"
	SETCZDC_DOWNLOAD_SPEED, // "Download Speed"
	SETCZDC_ERROR_COLOR, // "Error color"
	SETCZDC_H_DOWN_SPEED, // "And whole file speed exceeds"
	SETCZDC_I_DOWN_SPEED, // "Disconnect download if speed is below"
	SETCZDC_MAGNET_URI_HANDLER, // "Install Magnet URI handler on startup"
	SETCZDC_MIN_FILE_SIZE, // "And file size is more than"
	SETCZDC_NOTE_SMALL_UP, // "* Small Uploads Slots => Slots for filelist and Small Files."
	SETCZDC_PASSIVE_SEARCH, // "Always use passive mode for Search (Use only if you know what this doing !!!)"
	SETCZDC_PM_LINES, // "Lines from log on new PM"
	SETCZDC_PREVIEW, // "Preview"
	SETCZDC_PRIVATE_SOUND, // "Private message sound"
	SETCZDC_PROGRESSBAR_COLORS, // "Progressbar colors"
	SETCZDC_PROGRESSBAR_TEXT, // "Progressbar text colors"
	SETCZDC_REMOVE_FORBIDDEN, // "Remove Forbidden (Unfinished Kazaa, Win MX, GetRight, eMule, AirDC++)"
	SETCZDC_SLOW_DISCONNECT, // "Disconnecting slow downloads"
	SETCZDC_SMALL_FILES, // "Small file size"
	SETCZDC_SMALL_UP_SLOTS, // "Small Upload Slots"
	SETCZDC_STYLES, // "Available styles"
	SETCZDC_TEXT_COLOR, // "Text color"
	SETCZDC_TEXT_STYLE, // "Text style"
	SETCZDC_TIME_DOWN, // "More than"
	SETCZDC_TO, // "to"
	SETCZDC_UPLOAD, // "Upload"
	SETCZDC_UPLOAD_SPEED, // "Upload Speed"
	SETCZDC_WINAMP, // "Media Toolbar settings"
	SETCZDC_WINAMP_PATH, // "Media Player Path:"
	SETSTRONGDC_PARTIAL_SLOTS, // "Extra slots for uploading partially downloaded files"
	SETTINGS, // "Settings"
	SETTINGS_ADD_FOLDER, // "&Add folder"
	SETTINGS_ADLS_BREAK_ON_FIRST, // "Break on first ADLSearch match"
	SETTINGS_ADVANCED, // "Advanced"
	SETTINGS_ADVANCED_SUPPRESS_MAIN_CHAT, // "Suppress main chat"
	SETTINGS_ADVANCED3, // "Experts only"
	SETTINGS_ALLOW_UNTRUSTED_CLIENTS, // "Allow TLS connections to clients without trusted certificate"
	SETTINGS_ALLOW_UNTRUSTED_HUBS, // "Allow TLS connections to hubs without trusted certificate"
	SETTINGS_ANTI_FRAG, // "Use antifragmentation method for downloads"
	SETTINGS_APPEARANCE, // "Appearance"
	SETTINGS_ARGUMENT, // "Arguments"
	SETTINGS_AUTO_AWAY, // "Auto-away on minimize (and back on restore)"
	SETTINGS_AUTO_DROP_SEGMENTED_SOURCE, // "When segmented downloading only (more than 2 active sources)"
	SETTINGS_AUTO_FOLLOW, // "Automatically follow redirects"
	SETTINGS_AUTO_KICK, // "Automatically disconnect users who leave the hub"
	SETTINGS_AUTO_KICK_NO_FAVS, // "Don't automatically disconnect favorite users who leave the hub"
	SETTINGS_AUTO_OPEN, // "Auto-open at startup"
	SETTINGS_AUTO_PRIORITY_DEFAULT, // "Use Auto Priority by default"
	SETTINGS_AUTO_REFRESH_TIME, // "Auto refresh time"
	SETTINGS_AUTO_SEARCH, // "Automatically search for alternative TTH source every"
	SETTINGS_AUTO_SEARCH_AUTO_MATCH, // "Automatically match queue for auto search hits"
	SETTINGS_AUTO_SEARCH_LIMIT, // "Max sources for autosearch"
	SETTINGS_AUTO_SLOTS, // "Maximum auto opened"
	SETTINGS_AVIPREVIEW, // "File Preview"
	SETTINGS_BIND_ADDRESS, // "Bind address"
	SETTINGS_BIND_ADDRESS_HELP, // "Network interface for all connections"
	SETTINGS_BOLD_OPTIONS, // "Tab bolding on content change"
	SETTINGS_CERTIFICATES, // "Security Certificates"
	SETTINGS_CLEAR_SEARCH, // "Clear search box after each search"
	SETTINGS_COLOR_ALTERNATE, // "Search Alternate"
	SETTINGS_COLOR_FAVORITE, // "Favorite"
	SETTINGS_COLOR_IGNORED, // "Ignored"
	SETTINGS_COLOR_NORMAL, // "Normal"
	SETTINGS_COLOR_RESERVED, // "Has reserved slot"
	SETTINGS_COLORS, // "Other colors"
	SETTINGS_COMMAND, // "Command"
	SETTINGS_COMPRESS_TRANSFERS, // "Enable safe and compressed transfers"
	SETTINGS_CONFIGURE_HUB_LISTS, // "Configure Public Hub Lists"
	SETTINGS_CONFIRM_DIALOG_OPTIONS, // "Confirm dialog options"
	SETTINGS_CONFIRM_EXIT, // "Confirm application exit"
	SETTINGS_CONFIRM_HUB_REMOVAL, // "Confirm favorite hub removal"
	SETTINGS_CONFIRM_ITEM_REMOVAL, // "Confirm item removal in download queue"
	SETTINGS_CZDC, // "AirDC++"
	SETTINGS_CZDC_EXTRA_DOWNLOADS, // "Highest Priority Extra Download Slots"
	SETTINGS_DEBUG_COMMANDS, // "Debug commands"
	SETTINGS_DEFAULT_AWAY_MSG, // "Default away message"
	SETTINGS_DIRECT, // "Direct connection"
	SETTINGS_DIRECTORIES, // "Directories"
	SETTINGS_DISPLAY_DC_UPDATE, // "Don't announce new AirDC++ versions (version.xml is still downloaded)"
	SETTINGS_DONT_DL_ALREADY_SHARED, // "Don't download files already in share"
	SETTINGS_DOWNCONN, // "Dwnld attempts/second"
	SETTINGS_DOWNLOAD_DIRECTORY, // "Default download directory"
	SETTINGS_DOWNLOAD_LIMITS, // "Limits"
	SETTINGS_DOWNLOADS, // "Downloads"
	SETTINGS_DOWNLOADS_MAX, // "Maximum simultaneous downloads (0 = infinite)"
	SETTINGS_DOWNLOADS_SPEED_PAUSE, // "No new downloads if speed exceeds (kB/s, 0 = disable)"
	SETTINGS_EXPAND_QUEUE, // "Automatically expand folders in Queue"
	SETTINGS_EXTENSIONS, // "Extensions"
	SETTINGS_EXTERNAL_IP, // "External / WAN IP"
	SETTINGS_FAV_SHOW_JOINS, // "Only show joins / parts for favorite users"
	SETTINGS_FAVORITE_DIRS, // "Favorite download directories"
	SETTINGS_FAVORITE_DIRS_PAGE, // "Favorites"
	SETTINGS_FILE_NAME, // "Filename"
	SETTINGS_FILES_MAX, // "Maximum simultaneous files (0 = infinite)"
	SETTINGS_FILTER_MESSAGES, // "Filter kick and NMDC debug messages"
	SETTINGS_FILTER_ENTER, // "Activate search/userlist filter by pressing Enter"
	SETTINGS_FIREWALL_NAT, // "Firewall with manual port forwarding"
	SETTINGS_FIREWALL_PASSIVE, // "Firewall (passive, worst case)"
	SETTINGS_FIREWALL_UPNP, // "Firewall with UPnP (WinXP+ only)"
	SETTINGS_FORMAT, // "Format"
	SETTINGS_GENERAL, // "General"
	SETTINGS_GET_USER_COUNTRY, // "Get User Country"
	SETTINGS_HUB_USER_COMMANDS, // "Accept custom user commands from hub"
	SETTINGS_CHANGE, // "&Change"
	SETTINGS_IGNORE_HUB_PMS, // "Ignore private messages from the hub"
	SETTINGS_IGNORE_BOT_PMS, // "Ignore private messages from bots"
	SETTINGS_INCOMING, // "Incoming connection settings (see Help/FAQ if unsure)"
	SETTINGS_KEEP_LISTS, // "Don't delete file lists when exiting"
	SETTINGS_LANGUAGE_FILE, // "Language file"
	SETTINGS_LIMIT, // "Limits"
	SETTINGS_LOG_DIR, // "Log directory"
	SETTINGS_LOG_DOWNLOADS, // "Log downloads"
	SETTINGS_LOG_FILELIST_TRANSFERS, // "Log filelist transfers"
	SETTINGS_LOG_MAIN_CHAT, // "Log main chat"
	SETTINGS_LOG_PRIVATE_CHAT, // "Log private chat"
	SETTINGS_LOG_STATUS_MESSAGES, // "Log status messages"
	SETTINGS_LOG_SYSTEM_MESSAGES, // "Log system messages"
	SETTINGS_LOG_UPLOADS, // "Log uploads"
	SETTINGS_LOGGING, // "Logging"
	SETTINGS_LOGS, // "Logs"
	SETTINGS_MAX_COMPRESS, // "Max compression level"
	SETTINGS_MAX_HASH_SPEED, // "Max hash speed"
	SETTINGS_MAX_TAB_ROWS, // "Max tab rows"
	SETTINGS_MINIMIZE_ON_STARTUP, // "Minimize at program startup"
	SETTINGS_MINIMIZE_TRAY, // "Minimize to tray"
	SETTINGS_MOUSE_OVER, // "Mouse Over"
	SETTINGS_NAME, // "Name"
	SETTINGS_NETWORK, // "Connection settings"
	SETTINGS_NO_AWAYMSG_TO_BOTS, // "Don't send the away message to bots"
	SETTINGS_NORMAL, // "Normal"
	SETTINGS_ODC_SHUTDOWNTIMEOUT, // "timeout"
	SETTINGS_ONLY_HASHED, // "Note; Files appear in the share only after they've been hashed!"
	SETTINGS_OPEN_NEW_WINDOW, // "Open new window when using /join"
	SETTINGS_OPERACOLORS, // "Progressbar colors"
	SETTINGS_OPTIONS, // "Options"
	SETTINGS_OUTGOING, // "Outgoing connection settings"
	SETTINGS_OVERRIDE, // "Don't allow hub/UPnP to override"
	SETTINGS_PERSONAL_INFORMATION, // "Personal Information"
	SETTINGS_PM_BEEP, // "Make an annoying sound every time a private message is received"
	SETTINGS_PM_BEEP_OPEN, // "Make an annoying sound when a private message window is opened"
	SETTINGS_PM_HISTORY, // "PM history"
	SETTINGS_POPUNDER_FILELIST, // "Open new file list windows in the background"
	SETTINGS_POPUNDER_PM, // "Open new private message windows in the background"
	SETTINGS_POPUP_BOT_PMS, // "Open private messages from the hub in their own window"
	SETTINGS_POPUP_HUB_PMS, // "Open private messages from bots in their own window"
	SETTINGS_POPUP_PMS, // "Open private messages in their own window"
	SETTINGS_PORTS, // "Ports"
	SETTINGS_PRIO_AUTOPRIO, // "Priority settings - has higher priority than Autopriority"
	SETTINGS_PRIO_HIGH, // "High prio max size"
	SETTINGS_PRIO_HIGHEST, // "Highest prio max size"
	SETTINGS_PRIO_LOW, // "Low prio max size"
	SETTINGS_PRIO_LOWEST, // "Set lowest prio for newly added files larger than Low prio size"
	SETTINGS_PRIO_NORMAL, // "Normal prio max size"
	SETTINGS_PROMPT_PASSWORD, // "Popup box to input password for hubs"
	SETTINGS_PUBLIC_HUB_LIST, // "Public Hubs list"
	SETTINGS_PUBLIC_HUB_LIST_HTTP_PROXY, // "HTTP Proxy (for hublist only)"
	SETTINGS_PUBLIC_HUB_LIST_URL, // "Public Hubs list URL"
	SETTINGS_QUEUE, // "Queue"
	SETTINGS_RENAME_FOLDER, // "Rename"
	SETTINGS_REQUIRES_RESTART, // "Note; most of these options require that you restart AirDC++"
	SETTINGS_RESET, // "Reset"
	SETTINGS_SB_MAX_SOURCES, // "Max sources for match queue"
	SETTINGS_SEARCH_HISTORY, // "Search history"
	SETTINGS_SEGMENT, // "Segment Downloading"
	SETTINGS_SELECT_COLOR, // "Select color"
	SETTINGS_SELECT_TEXT_FACE, // "&Text style"
	SETTINGS_SELECT_WINDOW_COLOR, // "&Window color"
	SETTINGS_SEND_UNKNOWN_COMMANDS, // "Send unknown /commands to the hub"
	SETTINGS_SHARE_HIDDEN, // "Share hidden files"
	SETTINGS_SHARE_SIZE, // "Total size:"
	SETTINGS_SHARED_DIRECTORIES, // "Shared directories"
	SETTINGS_SHOW_INFO_TIPS, // "Show InfoTips in lists"
	SETTINGS_SHOW_JOINS, // "Show joins / parts in chat by default"
	SETTINGS_SHOW_PROGRESS_BARS, // "Show progress bars for transfers (uses some CPU)"
	SETTINGS_SHOW_SHELL_MENU, // "Show shell menu in finished transfers and Own FileList"
	SETTINGS_SKIP_ZERO_BYTE, // "Skip zero-byte files"
	SETTINGS_SOCKS5, // "SOCKS5"
	SETTINGS_SOCKS5_IP, // "Socks IP"
	SETTINGS_SOCKS5_PORT, // "Port"
	SETTINGS_SOCKS5_RESOLVE, // "Use SOCKS5 server to resolve host names"
	SETTINGS_SOCKS5_USERNAME, // "Login"
	SETTINGS_SORT_FAVUSERS_FIRST, // "Sort favorite users first"
	SETTINGS_SOUND, // "Sounds"
	SETTINGS_SOUNDS, // "Sounds"
	SETTINGS_SPEEDS_NOT_ACCURATE, // "Note; because of changing download speeds, this is not 100% accurate..."
	SETTINGS_STATUS_IN_CHAT, // "View status messages in main chat"
	SETTINGS_TCP_PORT, // "TCP"
	SETTINGS_TLS_PORT, // "TLS/TCP"
	SETTINGS_TEXT_STYLES, // "Colors & Fonts"
	SETTINGS_TIME_STAMPS, // "Show timestamps in chat by default"
	SETTINGS_TIME_STAMPS_FORMAT, // "Set timestamps"
	SETTINGS_TOGGLE_ACTIVE_WINDOW, // "Toggle window when selecting an active tab"
	SETTINGS_TOOLBAR, // "Toolbar"
	SETTINGS_TOOLBAR_ADD, // "Add -->"
	SETTINGS_TOOLBAR_IMAGE, // "Toolbar Images"
	SETTINGS_TOOLBAR_REMOVE, // "<-- Remove"
	SETTINGS_UDP_PORT, // "UDP Port"
	SETTINGS_UNFINISHED_DOWNLOAD_DIRECTORY, // "Unfinished downloads directory"
	SETTINGS_UPLOAD_LINE_SPEED, // "Line speed (upload)"
	SETTINGS_UPLOADS, // "Sharing"
	SETTINGS_UPLOADS_MIN_SPEED, // "Open an extra slot if speed is below (0 = disable)"
	SETTINGS_UPLOADS_SLOTS, // "Upload slots"
	SETTINGS_URL_HANDLER, // "Install URL handler on startup (to handle dchub:// links)"
	SETTINGS_USE_CTRL_FOR_LINE_HISTORY, // "Use CTRL for line history"
	SETTINGS_USE_OLD_SHARING_UI, // "Use old sharing user interface"
	SETTINGS_USE_SYSTEM_ICONS, // "Use system icons when browsing files (slows browsing down a bit)"
	SETTINGS_USE_TLS, // "Use TLS when remote client supports it (affects both clients and hubs)"
	SETTINGS_USE_VERTICAL_VIEW, // "Use vertical view by default"
	SETTINGS_USER_COLORS, // "User List Colors"
	SETTINGS_USER_COMMANDS, // "User Commands"
	SETTINGS_USER_MENU, // "User Menu Items"
	SETTINGS_WINDOWS, // "Windows"
	SETTINGS_WINDOWS_OPTIONS, // "Window options"
	SETTINGS_WRITE_BUFFER, // "Write buffer size"
	SETTINGS_SOCKET_IN_BUFFER, // "Socket read buffer"
	SETTINGS_SOCKET_OUT_BUFFER, // "Socket write buffer"
	SETTINGS_ZDC_PROGRESS_OVERRIDE, // "Override system colors"
	SETTINGS_ZDC_PROGRESS_OVERRIDE2, // "Override system colors"
	SHARED, // "Shared"
	SHARED_FILES, // "Shared Files"
	SHOW_POPUP_AWAY, // "Display popup in away mode only"
	SHOW_POPUP_MINIMIZED, // "Display popup when minimized only"
	SHUTDOWN, // "Shutdown computer"
	SHUTDOWN_ACTION, // "Shutdown action"
	SHUTDOWN_OFF, // "Shutdown sequence deactivated..."
	SHUTDOWN_ON, // "Shutdown sequence activated..."
	SIZE, // "Size"
	SIZE_EXACT, // "Exactly"
	SIZE_MIN, // "Min Size"
	SKIP_RENAME, // "New virtual name matches old name, skipping..."
	SLOT_GRANTED, // "Slot granted"
	SLOTS, // "Slots"
	SLOTS_SET, // "Slots set"
	SLOW_USER, // "Slow user"
	SMALL_FILE_SIZE_SET, // "Small file size set"
	SOCKS_AUTH_FAILED, // "Socks server authentication failed (bad login / password?)"
	SOCKS_AUTH_UNSUPPORTED, // "The socks server doesn't support login / password authentication"
	SOCKS_FAILED, // "The socks server failed establish a connection"
	SOCKS_NEEDS_AUTH, // "The socks server requires authentication"
	SOCKS_SETUP_ERROR, // "Failed to set up the socks server for UDP relay (check socks address and port)"
	SOUND_DOWNLOAD_BEGINS, // "Download begins"
	SOUND_DOWNLOAD_FINISHED, // "Download finished"
	SOUND_EXCEPTION, // "Unhandled Exception"
	SOUND_FAKER_FOUND, // "Faker found"
	SOUND_SOURCE_ADDED, // "Alternate source added"
	SOUND_TTH_INVALID, // "File is corrupted"
	SOUND_TYPING_NOTIFY, // "Typing sound"
	SOUND_UPLOAD_FINISHED, // "Upload finished"
	SOURCE_TOO_OLD, // "Remote client does not fully support TTH - cannot download"
	SOURCE_TYPE, // "Source Type"
	SPECIFY_SEARCH_STRING, // "Specify a search string"
	SPECIFY_SERVER, // "Specify a server to connect to"
	SPEED, // "Speed"
	SSL_ERROR, // "SSL Error"
	STARTED, // "Started"
	STATUS, // "Status"
	STEALTH_MODE, // "Emulate DC++ in this hub"
	STORED_PASSWORD_SENT, // "Stored password sent..."
	STRING_NOT_FOUND, // "String not found: "
	SUPPORTS, // "Supports"
	SUSPEND, // "Suspend"
	TABS_ON_TOP, // "Tabs on top"
	TAG, // "Tag"
	TARGET_FILE_EXISTS, // "File already exists at the target Download location"
	TARGET_FILENAME_TOO_LONG, // "Target filename too long"
	TARGET_REMOVED, // "Target removed"
	TiB, // "TiB"
	TCP_PORT_BUSY, // "Unable to open TCP/TLS port. File transfers will not work correctly until you change settings or turn off any application that might be using the TCP/TLS port"
	TEXT_MANUAL, // "Manual settings of number of segments"
	TIME, // "Time"
	TIME_LEFT, // "Time left"
	TIMESTAMP_HELP, // "\r\n- %a - Abbreviated weekday name\r\n- %A - Full weekday name\r\n- %b - Abbreviated month name\r\n- %B - Full month name\r\n- %c - Date and time representation appropriate for locale\r\n- %d - Day of month as decimal number (01 – 31)\r\n- %H - Hour in 24-hour format (00 – 23)\r\n- %I - Hour in 12-hour format (01 – 12)\r\n- %j - Day of year as decimal number (001 – 366)\r\n- %m - Month as decimal number (01 – 12)\r\n- %M - Minute as decimal number (00 – 59)\r\n- %p - Current locale's A.M./P.M. indicator for 12-hour clock\r\n- %S - Second as decimal number (00 – 59)\r\n- %U - Week of year as decimal number, with Sunday as first day of week (00 – 53)\r\n- %w - Weekday as decimal number (0 – 6; Sunday is 0)\r\n- %W - Week of year as decimal number, with Monday as first day of week (00 – 53)\r\n- %x - Date representation for current locale\r\n- %X - Time representation for current locale\r\n- %y - Year without century, as decimal number (00 – 99)\r\n- %Y - Year with century, as decimal number\r\n- %z, %Z - Either the time-zone name or time zone abbreviation, depending on registry settings; no characters if time zone is unknown\r\n- %% - Percent sign\r\n\r\nDefault: %H:%M:%S"
	TIMESTAMP_HELP_DESC, // "Timestamps Help"
	TIMESTAMPS_DISABLED, // "Timestamps disabled"
	TIMESTAMPS_ENABLED, // "Timestamps enabled"
	TOO_LARGE_LIST, // "Greater than maximum filelist size (256 MB)"
	TOO_MUCH_DATA, // "More data was sent than was expected"
	TOTAL, // "Total: "
	TRANSFERLISTDBLCLICKACTION, // "Transferlist double click action"
	TRANSFERRED, // "Transferred"
	TRUSTED_CERTIFICATES_PATH, // "Trusted certificates path"
	CERTIFICATES_CONSTUCTION, // "Under construction, restart AirDC++ to see effects..."
	CERTIFICATES_EXPERIMENTAL, // "Experimental feature, don't consider AirDC++ secure in any way"
	TTH_ALREADY_SHARED, // "A file with the same hash already exists in your share"
	TTH_INCONSISTENCY, // "TTH Inconsistency"
	TTH_ROOT, // "TTH Root"
	TWO_COLORS, // "Two colors"
	TYPE, // "Type"
	UC_SUBMENU, // "Place usercommands to submenu"
	UNABLE_TO_CREATE_THREAD, // "Unable to create thread"
	UNABLE_TO_OPEN_FILELIST, // "Unable to open filelist: "
	UNABLE_TO_RENAME, // "Unable to rename "
	UNABLE_TO_SEND_FILE, // "Unable to send file "
	UNFINISHED_FILE_NOT_FOUND, // "Unfinished file not found"
	UNFINISHED_FILE_TOO_SMALL, // "Unfinished file too small"
	UNIGNORE_USER, // "Unignore User"
	UNKNOWN, // "Unknown"
	UNKNOWN_COMMAND, // "Unknown command: "
	UNKNOWN_ERROR, // "Unknown error: 0x%x"
	UPDATE_CHECK, // "Update check"
	UPLOAD_FINISHED_IDLE, // "Upload finished, idle..."
	UPLOAD_STARTING, // "Upload starting..."
	UPLOADED_BYTES, // "Uploaded %s (%.01f%%) in %s"
	UPLOADED_TO, // " uploaded to "
	UPNP_FAILED_TO_CREATE_MAPPINGS, // "Failed to create port mappings. Please set up your NAT yourself."
	UPNP_FAILED_TO_GET_EXTERNAL_IP, // "Failed to get external IP via  UPnP. Please set it yourself."
	UPNP_FAILED_TO_REMOVE_MAPPINGS, // "Failed to remove port mappings"
	USE_EXPLORER_THEME, // "Use Explorer theme in listviews and treeviews"
	USER, // "User"
	USER_CMD_COMMAND, // "Command"
	USER_CMD_CONTEXT, // "Context"
	USER_CMD_FILELIST_MENU, // "Filelist Menu"
	USER_CMD_HUB, // "Hub IP / DNS (empty = all, 'op' = where operator)"
	USER_CMD_HUB_MENU, // "Hub Menu"
	USER_CMD_CHAT, // "Chat"
	USER_CMD_ONCE, // "Send once per nick"
	USER_CMD_PARAMETERS, // "Parameters"
	USER_CMD_PM, // "PM"
	USER_CMD_PREVIEW, // "Text sent to hub"
	USER_CMD_SEARCH_MENU, // "Search Menu"
	USER_CMD_TO, // "To"
	USER_CMD_TYPE, // "Command Type"
	USER_CMD_USER_MENU, // "User Menu"
	USER_CMD_WINDOW, // "Create / Modify Command"
	USER_CMD_DESCRIPTION, // "Command Types:\r\nSeparator: Adds a separator to the menu\r\nRaw: Sends raw command to the hub (experts only, end it with '|'!)\r\nChat: Sends command as if you were typing it in the chat\r\nPM: Sends command as if you sent it by pm\r\nContexts determine where the command is shown:\r\nHub Menu: Hub tab (at the bottom of the screen) right-click menu\r\nChat Menu: User right-click menu in chat and PM tab menu\r\nSearch Menu: Search right-click menu\r\nParameters:\r\nName: Name (use '\\' to create submenus)\r\nCommand: Command text (may contain parameters)\r\nHub: Hub ip as typed when connecting (empty = all hubs, \"op\" = hubs where you're op)\r\nTo: PM recipient\r\nOnly once: Send only once per user from search frame\r\nIn the parameters, you can use %[xxx] variables and date/time specifiers (%Y, %m, ...). The following are available:\r\n%[myNI]: your own nick\r\n%[userNI]: the users nick (user && search context only)\r\n%[userTAG]: user tag (user && search context only)\r\n%[userDE]: user description (user && search context only)\r\n%[userEM]: user email (user && search context only)\r\n%[userSS]: user shared bytes (exact) (user && search context only)\r\n%[userSSshort]: user shared bytes (formatted) (user && search context only)\r\n%[userI4]: user ip (if supported by hub)\r\n%[fileFN]: filename (search context only)\r\n%[line:reason]: opens up a window asking for \"reason\""
	USER_DESCRIPTION, // "User Description"
	USER_OFFLINE, // "User offline"
	USER_ONLINE, // "Running... (user online)"
	USER_WENT_OFFLINE, // "User went offline"
	USER_WENT_ONLINE, // "User went online"
	USERINFO, // "Info User"
	USERLIST_ICONS, // "Userlist Icons"
	USERLISTDBLCLICKACTION, // "Userlist double click action"
	USERS, // "Users"
	USERS_ONLINE, // "Running... (%d of %d users online)"
	VERSION, // "Version"
	VIDEO, // "Video"
	VIEW_AS_TEXT, // "View as text"
	VIRTUAL_NAME, // "Virtual name"
	VIRTUAL_NAME_EXISTS, // "Virtual directory name already exists"
	VIRTUAL_NAME_LONG, // "Name under which the others see the directory"
	WAITING, // "Waiting..."
	WAITING_FOR, // "Waiting for %i seconds before searching..."
	WAITING_TIME, // "Waiting time"
	WAITING_TO_RETRY, // "Waiting to retry..."
	WAITING_USER_ONLINE, // "Waiting (User online)"
	WAITING_USERS, // "Waiting Users"
	WAITING_USERS_ONLINE, // "Waiting (%d of %d users online)"
	WHATS_THIS, // "What's &this?"
	WHO_IS, // "Whois "
	WINAMP_HELP, // "/winamp - Works with 1.x, 2.x, 5.x (no WinAmp 3 support)\r\n- %[version]	Numerical Version (ex: 2.91)\r\n- %[state]	Playing state (ex: stopped/paused/playing)\r\n- %[title]		Window title from Winamp - if you want to change this for mp3s, Winamp > Pref > Input > MPEG > Title\r\n- %[rawtitle]	Window title from Winamp (if %[title] not working propertly)\r\n- %[percent]	Percentage (ex. 40%)\r\n- %[length]	Length in minutes:seconds (ex: 04:09)\r\n- %[elapsed]	Time elapsed in minutes:seconds (ex. 03:51)\r\n- %[bar]		ASCII progress bar, 10 characters wide no including brackets (ex. [----|-----])\r\n- %[bitrate]	Bitrate (ex. 128kbps)\r\n- %[sample]	Sample frequency (ex. 22kHz)\r\n- %[channels]	Number of channels (ex. stereo / mono)\r\nEmpty = Default String -> winamp(%[version]) %[state](%[title]) stats(%[percent] of %[length] %[bar])"
	WINAMP_HELP_DESC, // "Winamp Help"
	YES, // "Yes"
	ZONEALARM_WARNING, // "ZoneAlarm was detected in your computer.  It is frequently responsible for corrupted downloads and is the cause of many \"rollback inconsistency\" errors.  Please uninstall it and use an alternate product.  "
	ADLS_REGEXP, // "Regexp"
	BACKGROUND_IMAGE, // "Background image"
	MENU_RECONNECT_DISCONNECTED, // "Reconnect disconnected"
	SETTINGS_FUL_TABS, // "AirDC++\\Tabs"
	HUB_BOLD_TABS, // "Make tabs bold on status messages in Hubs"
	TAB_SHOW_ICONS, // "Show icons in tabs"
	BLEND_TABS, // "Blend tabs instead of using bold font"
	SETTINGS_SB_TAB_COLORS, // "Tab Colors"
	SETTINGS_SB_TAB_SIZE, // "Size of string to display in tabs"
	SETTINGS_BTN_COLOR, // "Select Color"
	SETTINGS_SB_DIRTY_BLEND, // "Blending"
	TAB_ACTIVE_BG, // "Active background color"
	TAB_ACTIVE_TEXT, // "Active text color"
	TAB_ACTIVE_BORDER, // "Active border color"
	TAB_INACTIVE_BG, // "Inactive background color"
	TAB_INACTIVE_BG_DISCONNECTED, // "Disconnected/Offline PM color"
	TAB_INACTIVE_TEXT, // "Inactive text color"
	TAB_INACTIVE_BORDER, // "Inactive border color"
	TAB_INACTIVE_BG_NOTIFY, // "Inactive notification color"
	FAV_NO_PM, // "Ignore private messages"
	HIDE_SHARE, // "Hide share in this hub"
	WINAMP_BACK, // "Back"
	WINAMP_PLAY, // "Play"
	WINAMP_PAUSE, // "Pause"
	WINAMP_NEXT, // "Next"
	WINAMP_STOP, // "Stop"
	WINAMP_VOL_UP, // "Volume up"
	WINAMP_VOL_HALF, // "Volume 50%"
	WINAMP_VOL_DOWN, // "Volume down"
	TOGGLE_TOOLBAR, // "Media Toolbar\tCtrl+4"
	WINAMP_SPAM, // "Post media spam to main chat"
	POPUP_TIME, // "Popup time"
	PM_PREVIEW, // "Show preview of private message on popup"
	POPUP_BACK_COLOR, // "&Back color"
	POPUP_FONT, // "&Msg text"
	POPUP_TITLE_FONT, // "&Title text"
	MAX_MSG_LENGTH, // "Max length"
	POPUP_IMAGE, // "Popup image"
	WMP_HELP, // "/wmp - Works with Windows Media Player 9+\r\n- %[version]	Version of Windows Media Player\r\n- %[fullversion]	Full version of Windows Media Player\r\n- %[status]	Pre-formatted status string from Windows Media Player\r\n- %[title]		Name of the currently playing item\r\n- %[elapsed]	Time elapsed in (HH:)MM:SS\r\n- %[percent]	Time elapsed presented as percentage from total length\r\n- %[bar]		ASCII progress bar, 10 characters wide no including brackets (ex. [----|-----])\r\n- %[length]	Full length of the current item in (HH:)MM:SS\r\n- %[artist]	Name of the artist for the currently playing item\r\n- %[album]	Name of the album the current song is from\r\n- %[genre]	Genre of the current media\r\n- %[bitrate]	Bitrate for the playing media\r\n- %[year]	Year of album publication (no WMP9 support)\r\n- %[size]		Size of the currently playing file\r\n- %[rating]	Users rating, represented with *'s (if available)\r\n\r\nEmpty = Default String -> +me %[title] at %[bitrate] <Windows Media Player %[version]>"
	WMP_HELP_DESC, // "Windows Media Player Help"
	ITUNES_HELP, // "/itunes - For iTunes media spamming\r\n- %[version]	Numerical Version (ex: 7.0.2.16)\r\n- %[album]	Name of the album the current track is from\r\n- %[artist]	Artist of the current track\r\n- %[title]		Name of the currently playing track\r\n- %[genre]	Genre of the currently playing track\r\n- %[elapsed]	Time elapsed in minutes:seconds\r\n- %[percent]	Time elapsed presented as percentage from total length\r\n- %[bar]		ASCII progress bar, 10 characters wide no including brackets (ex. [----|-----])\r\n- %[length]	Total length of the current track\r\n- %[bitrate]	Bitrate for the playing track (kbps)\r\n- %[frequency]	Frequency for the currently playing track (kHz)\r\n- %[year]	Year of publication/recording of the current track\r\n- %[size]		Size of the currently playing file\r\n- %[state]	Current state of iTunes (playing/stopped)\r\n\r\nEmpty = Default String -> +me playing: %[title] at %[bitrate] <iTunes %[version]>"
	ITUNES_HELP_DESC, // "iTunes Help"
	MPC_HELP, // "/mpc - For Media Player Classic media spamming\r\n- %[filename]	Name of the file currently playing\r\n- %[title]		Name of the currently playing item (without file extension)\r\n- %[size]		Size of the file currently playing\r\n- %[state]	Current state of Media Player Classic (playing/paused/stopped)\r\n- %[elapsed]	Time elapsed in minutes:seconds\r\n- %[percent]	Time elapsed presented as percentage from total length\r\n- %[bar]		ASCII progress bar, 10 characters wide no including brackets (ex. [----|-----])\r\n- %[length]	Total length of the current file\r\n\r\nEmpty = Default String -> +me playing: %[title] <Media Player Classic>"
	MPC_HELP_DESC, // "Media Player Classic Help"
	NO_MEDIA_SPAM, // "Selected player doesn't support media spams"
	WINAMP_START, //  "Start Media Player"
	WINAMP_MENU, // "Winamp"
	WINAMP_REFRESH, // "Refresh"
	WINAMP_ARTIST, // "Artist"
	WINAMP_TITLE, // "Title"
	WINAMP_LENGTH, // "Length"
	WINAMP_LOCATION, // "Path"
	BROWSEW, // "Browse.."
	SETTINGS_IGNORE, // "Ignore"
 	ALREADY_IGNORED, // "Pattern is already in the list"
	IGNORE_CLEAR, // "Clear"
	USE_REGEXP_OR_WC, // "Use regexp or wildcards"
	IGNORED_USERS, // "Ignored users"
	SETTINGS_AIRDCPAGE, // "AirDC++"
	INCOMING, // "incoming"
	OUTGOING, // "outgoing"
	BEGIN, // "Begin"
	END, // "End"
	NAT_SORT, // "Use natural sorting"
	SETAIRDC_ANTI_VIR, // "Virus scan after download finished"
	UPDATE_IP, // "Update IP on startup"
	SETTINGS_SERVER_COMMANDS, // "Show Server Commands as status messages"
	SET_CLIENT_COMMANDS, // "Show Client Commands as status messages"
	SETTINGS_AIRDOWNLOADS, // "AirDownloads"
	SETTINGS_AIRDOWNLOADS_SEGMENT, // "Segments"
	SETTINGS_AIRDOWNLOADS_SEGMENT_SIZE, // "Minimum segment size"
	ST_SKIPLIST_SHARE, // "Don't share the following files (separate files with '|', wildcards allowed):"
	ST_SKIPLIST_SHARE_BORDER, // "Skiplist Share"
	ST_MINISLOTS_EXT, // "Grant minislot automatically for the following file extensions: (separate extensions with '|', wildcards allowed)"
	SB_MINISLOTS, // "Minislots"
	SETTINGS_AIRSHARING, // "AirSharing"
	SETTINGS_SB_SKIPLIST_DOWNLOAD, // "Skiplist"
	SETTINGS_ST_PATHS, // "Separate paths with |"
	SETTINGS_SB_HIGH_PRIO_FILES, // "High priority files - Has higher Priority over other Priority Settings"
	REMOVE_FILE, // "Remove file from queue"
	SETTINGS_FUL_HIGHLIGHT, // "AirDC++\\Highlight"
	HIGHLIGHT_MATCH_TYPES, // "Begins,Contains,Ends,Equals"
	HIGHLIGHTLIST_HEADER, // "String to match"
	HIGHLIGHT_ADD, // "Add..."
	HIGHLIGHT_CHANGE, // "Change..."
	HIGHLIGHT_DIALOG_TITLE, // "Highlight settings"
	HIGHLIGHT_TEXT_STYLES, // "Text styles"
	HIGHLIGHT_MATCH_OPTIONS, // "Match options"
	HIGHLIGHT_ACTIONS, // "Actions"
	HIGHLIGHT_TEXT_TO_MATCH, // "Text to match"
	HIGHLIGHT_OK, // "OK"
	HIGHLIGHT_CANCEL, // "Cancel"

	SETTINGS_ST_MATCH_TYPE, // "Match Type"
	SETTINGS_BTN_UPDATE, // "Update"
	SETTINGS_BTN_MOVEUP, // "Move Up"
	SETTINGS_BTN_MOVEDOWN, // "Move Down"
	SETTINGS_BTN_BGCOLOR, // "Background Color"
	SETTINGS_SELECT_SOUND, // "Select Sound File"
	SETTINGS_POPUP, // "Display Popup"
	SETTINGS_PLAY_SOUND, // "Play Sound"
	SETTINGS_FLASH_WINDOW, // "Flash Window"
	SETTINGS_INCLUDE_NICK, // "Include Nick"
	SETTINGS_WHOLE_LINE, // "Whole Line"
	SETTINGS_ENTIRE_WORD, // "Entire Word"
	SETTINGS_TAB_COLOR, // "Change Tabcolor"
	SETTINGS_LASTLOG, // "Add to history"
	BOLD, // "Bold"
	ITALIC, // "Italic"
	UNDERLINE, // "Underline"
	STRIKEOUT, // "Strikeout"
	PRESET, // "Presets"
	PRESET_ADD_ALL, // "Add all"
	PRESET_MY_NICK, // "My nick"
	PRESET_MY_MESSAGES, // "My messages"
	PRESET_USERS, // "Users"
	PRESET_TIMESTAMP, // "Timestamps"
	PRESET_URLS, // "Urls"
	PRESET_ME, // "/me"
	PRESET_STATUS, // "Status messages"
	PRESET_JOINS, // "Joins"
	PRESET_PARTS, // "Parts"
	PRESET_RELEASES, // "Releases"
	PRESET_WINAMP_SPAM, // "Winamp spam"
	PRESET_KICKED_USERS, // "Kicked users"
	PRESET_DCHUB, // "Hub links"
	SETTINGS_BTN_TEXTCOLOR, // "Text Color"
	ADD_EMPTY, // "Can't add an empty string"
	BAD_REGEXP, // "Badly formatted regular expression"
	AIRDC, // "AirDC++"
	FLASH_WINDOW_ON_PM, // "Flash window on PM"
	FLASH_WINDOW_ON_NEW_PM, // "Flash window on PM only if it's from a new user"
	FLASH_WINDOW_ON_MYNICK, // "Flash window on my nick in PM/Hub"

	SETTINGS_AIRSEARCH, // "Search"
	AUTOSEARCH_ENABLE, // "Enable search for specified files / TTH"
	AUTOSEARCH_ENABLE_TIME, // "Automatically search every"
	AUTOSEARCH_RECHECK_TEXT,// "Recheck All items after"
	SETTINGS_VALUE, // "Value"
	ACTION, // "Action"
	LINE_EMPTY, // "Line must not be empty"
	SEARCH_TTH, // "Search by TTH"
	PAUSE, // "Pause"
	SETTINGS_AIRAPPEARANCE, // "AirDC++\\Appearance"
	GET_IP, // "Get IP"
	USE_HIGHLIGHT, // "Use Highlights"
	SETTINGS_DUPES, // "Dupes Background Color"
	SETTINGS_DUPE_DESCRIPTION, // "Background color used in file lists to show files that are already shared"
	SETTINGS_SHOW_QUEUE_BARS, // "Show Progress bars in Queue"
	SETTINGS_LANGUAGE, // "Language"	
	SETTINGS_LSWE, // "Swedish"
	SETTINGS_LFIN, // "Finnish"
	SETTINGS_LITA, // "Italian"
	SETTINGS_LHUN, // "Hungarian"
	SETTINGS_LRO, // "Romanian"
	SETTINGS_LDAN, // "Danish"
	SETTINGS_LENG, // "English"
	SETTINGS_LPOR, // "Portuguese"
	SETTINGS_LPOL, // "Polish"
	SETTINGS_LFR, // "French"
	SETTINGS_LD, // "Dutch"
	OPEN_FIRST, // "Open First X Hubs at Startup"
	SEARCH_BY_TTH, // "Search by TTH"
	PASTE, // "Paste"
	SEARCH_SITES, // "Search Sites"
	SEARCH_GOOGLE, // "Google"
	SEARCH_GOOGLE_TITLE, // "Google (title only)"
	SEARCH_GOOGLE_FULL, // "Google (full release name)"
	SEARCH_TVCOM, // "TV.com"
	SEARCH_URL, // "as Url"
	SEARCH_IMDB, // "Imdb"
	SEARCH_METACRITIC, // "Metacritic"
	BLACK_THEME, // "Black Theme"
	IMPORT_THEME, // "Import Theme"
	EXPORT_THEME, // "Export Theme"
	SETTINGS_LNOR, // "Norwegian"
	REFRESH_FILE_LIST, // "Refresh file list"

	USE_REGEXP, // "Use Regexp"
	FAV_DL_SPEED, // "Add User to Favorites If Download Speed is over"
	FILEWDIR, // "Filename with path"
	CASE_SENSITIVE, // "Case sensitive"
	INVALID_REGEXP, // "Invalid RegExp!"
	CASE_INSENSITIVE_REGEXP, // "Case insensitive RegExp"
	MATCH, // "Match"
	IDC_MIN_SEGMENT_SIZE_LABEL, // "Minimum segment size"
	IDC_SETTINGS_SEGMENTS, // "Segments"
	RAW, // "Raw"
	DIRECTORY_SHARED, // "Directory already shared"
	DIRECTORY_PARENT, // "Remove all subdirectories before adding this one"
	SETTINGS_OVERLAP_CHUNKS, // "Overlap slow chunks by faster user when file is going to be finished"
	OPEN_LOGS_INTERNAL, // "Open log files internally (performance may decrease when opening huge log files)"
	MENU_OPEN_SYSTEMLOG, // "Open System Log"
	NAME, // "Name"
	SETTINGS_DUPE_TEXT, // "Use Dupe Color for Text instead of Background"
	INFO, // "Info"
	SYSTEM_LOG, // "System Log"
	OPEN_SYSTEM_LOG, // "Open system log"
	NO_SYSTEM_LOG, // "No system log exists"
	FILE_LIST_PARTIAL, // "file list partial"
	AUTOSEARCH_DLG, // "Add/Change Autosearch String"
	PREVIEW_DLG, // "Add/Change Preview Command"
	POPUP_COLORS, // "Popup colors"

	PROPPAGE_GENERAL_TEXT, // "General text"
	PROPPAGE_GENERAL_CHAT_TEXT, // "General chat text"
	PROPPAGE_MY_NICK, // "My nick"
	PROPPAGE_MY_OWN_MSG, // "My own message"
	PROPPAGE_PRIVATE_MSG, // "Private message"
	PROPPAGE_SYSTEM_MSG, // "System message"
	PROPPAGE_SERVER_MSG, // "Server message"
	PROPPAGE_TIMESTAMP, // "Timestamp"
	PROPPAGE_STYLE_TIMESTAMP, // "The style for timestamp"
	PROPPAGE_URL, // "URL"
	PROPPAGE_FAV_USER, // "Favorite user"
	PROPPAGE_OPERATOR, // "Operator"
	PROPPAGE_NORM, // "Other users"
	MAX_RESIZE_LINES, // "Max resize lines"
	DONT_SHARE_EMPTY_DIRS, // "Don't share empty directories"
	ONLY_SHARE_FULL_DIRS, // "Only share fully hashed directories"
	ST_REFRESH_DELAY, // "Refresh Delay After client starts"
	ST_AIRDC_SLOT, // "Extraslots to fellow AirDC++ users(version 2.05->)"
	SETTINGS_DUPE_SEARCH, // "Use Dupe Color in Search"
	SETTINGS_LRUS, // "Russian"
	FILE_ALREADY_SHARED, // "Trying to Download File already shared! File: "
	PASSWD_PROTECT_STATIC, // "Client protection"
	PASSWD_PROTECT_CHCKBOX, // "Enable password protection"
	PASSWORD_DESC, // "Please enter password:"
	PASSWORD_TITLE, // "Authentification Required To Preform This Action"
	UNLOCK, // "Unlock"
	PASSWD_PROTECT_TRAY_CHCKBOX, // "Protect Tray"
	NOTE, // "Note; If you disable password protection your password will be reset!"
	READD_ALL, // "Readd all Sources"
	HUB_NOT_PROTECTED, // "No password was required/provided at login, disconnecting hub."
	DISALLOW_CONNECTION_TO_PASSED_HUBS, // "Automatically disconnect hubs if not registered"
	DONT_SHARE_DOWNLOAD_DIRECTORY, // "The download directory cannot be shared"
	TOTAL_TIME_LEFT, // "Total Time left"
	BOLD_HUB_TABS_ON_KICK, // "Bold hub's tabs on kick messages"
	SKIPLIST, // "Skiplist, Wildcards, Separate | "
	SETTINGS_SEARH_SKIPLIST_PRESET, // "Presets for Search Skiplist, Separate with | *wildcards allowed"
	SETTINGS_ASEARCH, // "Auto Search"
	PRESET1, // "Preset1"
	PRESET2, // "Preset2"
	PRESET3, // "Preset3"
	DIRECTORY_IS_HIDDEN, // "Directory is hidden"
	DIRECTORY_NOT_FOUND, // "Directory not shared"
	GROUP, // "Group"
	DISABLE_REFRESH_ON_SHAREPAGE, // "Disable Refresh on Exit Share Settings"
	REFRESH_VNAME_ON_SHAREPAGE, // "Refresh Only Changed on Exit Share Settings"
	QUEUE_SIZE, // "Queue Size"
	AUTO_ADD_SOURCE, // "Automatically add download sources from search"
	UPDATE, // "Update"
    UPNP_NO_IMPLEMENTATION, // "No UPnP implementation available"
	UPNP_SUCCESSFULLY_CREATED_MAPPINGS, // "Successfully created port mappings"
	UPDATE_CLIENT, // "Update file has finished downloading. Do you Wish to update? (AirDC++ will exit)"
	UPDATE_FILE_DETECTED, // "Updater File detected. Do you Wish to update? (AirDC++ will exit)"
	TEST_WRITE, // "Test Write to AirDC++ folders on startup"
	SETTINGS_INCOMING_REFRESH_TIME, // "Incoming Refresh Time"
	SETTINGS_USE_ADLS, // "Use ADLSearch on Filelists"
	SETTINGS_USE_ADLS_OWN_LIST, // "Use ADLSearch on Own FileList"
	SETTING_DONT_DL_ALREADY_QUEUED, // "Dont Download Files already in Queue"
	FILE_WITH_SAME_TTH, // "File with same TTH allready exists in Queue"
	FAV_SHOW_JOIN, // "Show User Joins / Parts"
	UPNP_REMOVED_MAPPINGS, // "Successfully removed port mappings"
	SETTINGS_DOWNLOADS_EXPAND, // "Auto Expand Downloads in TransferView"
	SYSTEM_SHOW_FINISHED_UPLOADS, // "Show Finished Uploads in System Log"
	SYSTEM_SHOW_FINISHED_DOWNLOADS, // "Show Finished Downloads in System Log"
	WIZARD, // "Settings Wizard"
	FORMAT_RELEASE, // "Format Release Names as Links in chat"
	COPY_DIRECTORY, // "Copy Directory"
	SEARCH_FOR_ALTERNATES_DIR, // "Search Directory for alternatives"
	ERROR_HASHING_CRC32, // "calculated CRC32 does not match the one found in SFV file."
	SETTINGS_SHARE_SFV, // "Don't perform SFV check for files being hashed into share"
	SEARCH_DIRECTORY, // "Search Directory"
	LAST // @DontAdd
};
