#include "stdinc.h"
#include "DCPlusPlus.h"
#include "ResourceManager.h"
std::string dcpp::ResourceManager::strings[] = {
"EN_Example.xml", 
"1.00", 
"Active", 
"Enabled / Search String", 
"&Add", 
"Add as source", 
"Add finished Bundles to share instantly (if shared)", 
"Add To Favorites", 
"Add to Queue", 
"Added", 
"Automatic Directory Listing Search", 
"Destination Directory", 
"Discard", 
"Download Matches", 
"Enabled", 
"Full Path", 
"ADLSearch Properties", 
"Search String", 
"Max FileSize", 
"Min FileSize", 
"Search Type", 
"Size Type", 
"All", 
"All 3 users offline", 
"All 4 users offline", 
"All download slots taken", 
"All file slots taken", 
"All %d users offline", 
"Searching TTH alternates for: ", 
"-- WARNING --\r\n-- You are in active mode, but have activated passive search. --\r\n-- Don't use passive search if you have search results without this option --\r\n-- because you don't get search result from passive clients !!! --\r\n-- Turn it off in settings => AirDC++ => Always use Passive Mode for Search --\r\n", 
"Allow NAT Traversal for connections with passive users", 
"Any", 
"At least", 
"At most", 
"Audio", 
"Auto", 
"Auto connect / Name", 
"Auto grant slot / Nick", 
"Automatic", 
"Average/s: ", 
"Upload Speed", 
"AWAY", 
"Away mode off", 
"Away mode on: ", 
"B", 
"Popups", 
"Bitzi Lookup", 
"Segment Block Finished, waiting...", 
"Both users offline", 
"Browse...", 
"&Browse...", 
"Browse file list", 
"Bumped", 
"Cancel", 
"Generated new TLS certificate", 
"Certificate not trusted", 
"TLS disabled, failed to generate certificate:", 
"CID", 
"Cipher", 
"Clear chat", 
"Client", 
"Close", 
"Close connection", 
"Collapse All", 
"User is OP", 
"Passive user", 
"Maximum command length exceeded", 
"Comment", 
"Compressed", 
"Error during compression", 
"&Configure", 
"Configured Public Hub Lists", 
"&Connect", 
"Connect to all users", 
"Connect to hub", 
"Connected", 
"Connecting...", 
"Connecting (forced)...", 
"Connecting to", 
"Connecting to server", 
"Connection", 
"Connection closed", 
"Enable automatic incoming connection type detection", 
"Connection error", 
"Connection timeout", 
"Continue Search", 
"Copy", 
"Copy All", 
"Copy description", 
"Copy email address", 
"Copy Exact Share", 
"Copy address to clipboard", 
"Copy IP", 
"Copy actual line", 
"Copy magnet link to clipboard", 
"Copy nick", 
"Copy Nick+IP", 
"Copy TAG", 
"Copy URL", 
"Use Coral network when downloading hub lists (improves reliability)", 
"Corruption detected for TTH: %s, at position %d", 
"Could not open target file: ", 
"Count", 
"Country", 
"Hashing", 
"Current version", 
"Current language", 
"Data retrieved", 
"Error during decompression", 
"Default", 
"Description", 
"Destination", 
"Directory", 
"Directory or directory name already exists", 
"Disable sounds", 
"Disabled", 
"Disconnect all users", 
"Disconnect user(s)", 
"Disconnected", 
"Disconnected user leaving the hub: ", 
"Document", 
"Done", 
"Don't begin new segment if overall file speed is over", 
"Don't remove /password before your password", 
"The temporary download directory cannot be shared", 
"Download", 
"Download failed: ", 
"Download finished, idle...", 
"Download queue", 
"Download starting...", 
"Download to...", 
"Download whole directory", 
"Download whole directory to...", 
"Download with priority...", 
"Downloaded", 
"Downloaded %s (%.01f%%) in %s", 
" downloaded from ", 
"Downloaded parts", 
"Downloading...", 
"Downloading public hub list...", 
"Downloading list...", 
"Downloads running, please disconnect them", 
"Duplicate source", 
"EiB", 
"&Edit", 
"E-Mail", 
"Enable segmented downloads", 
"Please enter a nickname in the settings dialog!", 
"Please enter a password", 
"Enter search string", 
"Error creating hash data file: ", 
"Error creating adc registry key", 
"Error creating dchub registry key", 
"Error creating magnet registry key", 
"Error hashing ", 
"Error saving hash data: ", 
"Errors", 
"Exact Share", 
"Exact size", 
"Executable", 
"Expand All", 
"Expand search results", 
"Slot ratio", 
"Extra slots set", 
"Failed to shutdown!", 
"Failed to load certificate file", 
"Failed to load private key", 
"Join/part of favorite users showing off", 
"Join/part of favorite users showing on", 
"Favorite name", 
"Under what name you see the directory", 
"Favorite hub added", 
"Hub already exists as a favorite", 
"This hub is not a favorite hub", 
"Identification (leave blank for defaults)", 
"Favorite Hub Properties", 
"Connection", 
"Favorite hub removed", 
"Favorite Hubs", 
"Favorite user added", 
"Favorite Users", 
"Favorite user online", 
"File", 
"File is already finished", 
"file list", 
"Subtract list", 
"File list refresh failed: ", 
"File list refresh finished", 
"File list refresh in progress, please wait for it to finish before trying to refresh again", 
"File list refresh initiated", 
"File not available", 
"File type", 
"A file with a different size already exists in the queue", 
"A file with diffent tth root already exists in the queue", 
"Filename", 
"Files", 
"files left", 
"files/h", 
"F&ilter", 
"Filtered", 
"Find", 
"Download finished: %s", 
"Finished Downloads", 
"Upload finished: %s To: %s", 
"Finished Uploads", 
"Folder", 
"Forbidden", 
"File with '$' cannot be downloaded and will not be shared: ", 
"Force attempt", 
"GiB", 
"Generate certificates", 
"Get file list", 
"Go to directory", 
"Grant extra slot (10 min)", 
"Grant extra slot (day)", 
"Grant extra slot (hour)", 
"Grant extra slot (week)", 
"Extra Slots", 
"Group search results by TTH", 
"Hash database", 
"Creating file index...", 
"Run in background", 
"Statistics", 
"Please wait while AirDC++ indexes your files (they won't be shared until they've been indexed)...", 
"Unable to read hash data file", 
"Hash database rebuilt", 
"Hashing failed: ", 
"Finished hashing: ", 
"Hibernate", 
"High", 
"Highest", 
"History", 
"Hits", 
"Hit Ratio: ", 
"Hits: ", 
"Hub", 
"Address", 
"Hub connected", 
"Hub disconnected", 
"Hublist", 
"Hub list downloaded...", 
"Edit the hublist", 
"Hub list loaded from cache...", 
"Name", 
"Hub / Connections", 
"Hub Topic :", 
"Users", 
"Cached hub list is corrupted or unsupported...", 
"Downloaded hub list is corrupted or unsupported...", 
"Hubs", 
"Chat double click on user action", 
"zero bytes real size", 
"Shared forbidden file : %s", 
"filelist was inflated %s times", 
"Choose folder", 
"Ignore TTH searches", 
"Ignore User", 
"Ignored message: ", 
"Hub address cannot be empty.", 
"Integrity check: %s (%s)", 
"Invalid file list name", 
"Invalid number of slots", 
"Invalid size", 
"Invalid target file (missing directory, check default download directory setting)", 
"Full tree does not match TTH root", 
"Ip: ", 
"Ip", 
"Items", 
"Join/part showing off", 
"Join/part showing on", 
"Joins: ", 
"KiB", 
"kB/s", 
"Keep finished files in the queue", 
"Kick user(s)", 
"Kick user(s) with filename", 
"A file of equal or larger size already exists at the target location", 
"Hub (last seen on if offline)", 
"Last change: ", 
"Time last seen", 
"Latest version", 
"Download Language", 
"left", 
"Left color", 
"Application ""%s"" caused an unhandled exception in AirDC++. Please uninstall it, upgrade it or use an alternate product.", 
"Upload Limit", 
"Listening socket failed (you need to restart AirDC++): ", 
"File list loaded in ", 
"Loading AirDC++, please wait...", 
"Loading file list, this may take a while if the list is large.", 
"Lock", 
"Log off", 
"Low", 
"Lowest", 
"Name:", 
"Application:", 
"Arguments: (%[file] %[dir] available)", 
"Apply to Extensions: (avi;mov;divx)", 
"Ask for Magnet action", 
"Filename:", 
"File Hash:", 
"Do nothing", 
"Add this file to your download queue", 
"Do the same action next time without asking", 
"Start a search for this file", 
"File Size:", 
"A MAGNET link was given to AirDC++, but it didn't contain a valid file hash for use on the Direct Connect network.  No action will be taken.", 
"AirDC++ has detected a MAGNET link with a file hash that can be searched for on the Direct Connect network.  What would you like to do?", 
"MAGNET Link detected", 
"Download files from the Direct Connect network", 
"AirDC++", 
"URL:MAGNET URI", 
"Manage Groups", 
"Match queue", 
"Max Hubs", 
"Max number of segments", 
"Max Size", 
"Max Users", 
"Max hubs", 
"Max users", 
"MiB", 
"MBits/s", 
"MB/s", 
"About AirDC++", 
"ADL Search", 
"Arrange icons", 
"Cascade", 
"CDM Debug Messages", 
"Close all file list windows", 
"Close all offline PM windows", 
"Close all PM windows", 
"Close all search windows", 
"Close disconnected", 
"AirDC++ Discussion forum", 
"Donate", 
"&Download Queue\tCtrl+D", 
"E&xit", 
"Frequently asked questions", 
"&Favorite Hubs\tCtrl+F", 
"Favorite &Users\tCtrl+U", 
"&File", 
"&Recent Hubs", 
"Follow last redirec&t\tCtrl+T", 
"Indexing progress", 
"&Help", 
"GeoIP database update", 
"Translations", 
"AirDC++ Homepage", 
"Horizontal Tile", 
"Minimize &All", 
"Network Statistics", 
"&Notepad\tCtrl+N", 
"Open downloads directory", 
"Open file list...\tCtrl+L", 
"Match downloaded lists", 
"Open own list", 
"&Public Hubs\tCtrl+P", 
"&Quick Connect ...\tCtrl+Q", 
"&Reconnect\tCtrl+R", 
"Refresh file list\tCtrl+E", 
"Restore All", 
"&Search\tCtrl+S", 
"Search spy", 
"Settings...", 
"Show", 
"&Status bar\tCtrl+2", 
"&Toolbar\tCtrl+1", 
"T&ransfers\tCtrl+3", 
"&Transfers", 
"Get TTH for file...", 
"Vertical Tile", 
"&View", 
"&Window", 
"Menu bar", 
"Min Share", 
"Min Slots", 
"Minimum search interval", 
"Min share", 
"Min slots", 
"Minutes", 
"Mode", 
"Move/Rename", 
"Move &Down", 
"Move &Up", 
"My nick in mainchat", 
"Network Statistics", 
"&New...", 
"Remove user from queue, if speed is below", 
"Next", 
"Nick", 
"Your nick was already taken, please change to something else!", 
" (Nick unknown)", 
"No", 
"TLS disabled, no certificate file set", 
"No directory specified", 
"You're trying to download from yourself!", 
"No errors", 
"No free block", 
"No full tree available", 
"Hub log not exist", 
"User log not exist", 
"No matches", 
"No needed part", 
"No slots available", 
"No users", 
"No users to download from", 
"None", 
"Normal", 
"Not listening for connections - please restart AirDC++", 
"Notepad", 
"segment(s)", 
"Offline", 
"OK", 
"Online", 
"Only users with free slots", 
"Only results with TTH root", 
"Only where I'm op", 
"Open", 
"Open download page?", 
"Open folder", 
"Open hub log", 
"Open user log", 
"Overlap slow chunks by faster user when file is going to be finished", 
"Overlapped by faster user", 
"Own certificate file", 
"Parts: ", 
"Param with same name already exists!", 
"Passive user", 
"Password", 
"Path", 
"Pause Search", 
"Paused", 
"PiB", 
"Picture", 
"Play", 
"Show popup on download failed", 
"Show popup on download finished", 
"Show popup on download begins", 
"Show popup on favorite user connected", 
"Show popup on hub connected", 
"Show popup on hub disconnected", 
"Show popup on new private message", 
"Show popup on private message", 
"Popup type", 
"Balloon popup", 
"Custom popup", 
"Splash popup", 
"Window popup", 
"Show popup on upload finished", 
"Port: ", 
"Power off", 
"Press the follow redirect button to connect to ", 
"Preview", 
"Previous folders", 
"Priority", 
"Private key file", 
"Private message", 
"Private message from ", 
"Transfer progressbar - background", 
"Transfer progressbar - decompressed part", 
"Queue progressbar - done chunks", 
"Queue progressbar - downloaded bytes", 
"Queue progressbar - running chunks", 
"Transfer progressbar - actual segment", 
"Queue progressbar - verified chunks", 
"Use oDC style of progressbar in Transfers", 
"&Properties", 
"Public Hubs", 
"Purge", 
"RegExp Tester", 
"It's a match!", 
"It's not a match.", 
"Invalid RegExp!", 
"RegExp", 
"Queued: ", 
"Quick Connect", 
"Rating", 
"Ratio", 
"Readd source", 
"Really exit?", 
"Really remove?", 
"Reason", 
"Reboot", 
"Recent Hubs", 
"Recheck integrity", 
"Redirect request received to a hub that's already connected", 
"Redirect user(s)", 
"&Refresh", 
"Refresh user list", 
"Reliability", 
"Requesting", 
"Requesting file list", 
"&Remove", 
"Remove all", 
"Remove extra slot", 
"Remove user from queue", 
"Remove offline users", 
"Remove source", 
" renamed to ", 
"Report user", 
"Show auto search for alternates in System Log", 
"Resume", 
"Retrieving data", 
"Right color", 
"Running...", 
"Search", 
"Search for", 
"Search for alternates", 
"Search for file", 
"Search in results", 
"Search options", 
"Search spam detected from ", 
"Search Spy", 
"Search String", 
"Searching for ", 
"Seconds", 
"Request to seek beyond the end of data", 
"Segment", 
"Segments", 
"Select all", 
"Select user in list", 
"Send private message", 
"Send public message", 
"Separator", 
"Server", 
"Back color", 
"Default style", 
"Enable slow downloads disconnecting", 
"Download Speed", 
"Error color", 
"Disconnect download if speed is below", 
"Install Magnet URI handler on startup", 
"And file size is more than", 
"* Small Uploads Slots => Slots for filelist and Small Files.", 
"Always use passive mode for Search (Use only if you know what this doing !!!)", 
"Lines from log on new PM", 
"Preview", 
"Private message sound", 
"Progressbar colors", 
"Progressbar text colors", 
"Remove Forbidden (Unfinished Kazaa, Win MX, GetRight, eMule, AirDC++)", 
"Disconnecting slow downloads", 
"Small file size", 
"Small Upload Slots", 
"Available styles", 
"Text color", 
"Text style", 
"More than", 
"to", 
"Upload", 
"Upload Speed", 
"Media Toolbar settings", 
"Media Player Path:", 
"Extra slots for uploading partially downloaded files", 
"Settings", 
"&Add folder", 
"Break on first ADLSearch match", 
"Advanced", 
"Suppress main chat", 
"Experts only", 
"Allow TLS connections to clients without trusted certificate", 
"Allow TLS connections to hubs without trusted certificate", 
"Use antifragmentation method for downloads", 
"Appearance", 
"Arguments", 
"Auto-away on minimize (and back on restore)", 
"Automatically follow redirects", 
"Automatically disconnect users who leave the hub", 
"Don't automatically disconnect favorite users who leave the hub", 
"Auto-open at startup", 
"Use Auto Priority by default", 
"Auto refresh time", 
"Max sources for autosearch", 
"Maximum auto opened", 
"File Preview", 
"Bind address", 
"Network interface for all connections", 
"Tab bolding on content change", 
"Security Certificates", 
"Clear search box after each search", 
"Search Alternate", 
"Favorite", 
"Ignored", 
"Normal", 
"Has reserved slot", 
"Other colors", 
"Command", 
"Enable safe and compressed transfers", 
"Configure Public Hub Lists", 
"Confirm dialog options", 
"Confirm application exit", 
"Confirm favorite hub removal", 
"Confirm item removal in download queue", 
"AirDC++", 
"Highest Priority Extra Download Slots", 
"Default away message", 
"Direct connection", 
"Directories", 
"Don't announce new AirDC++ versions (version.xml is still downloaded)", 
"Don't download files already in share", 
"Dwnld attempts/second", 
"Default download directory", 
"Downloads", 
"Maximum simultaneous downloads (0 = infinite)", 
"No new downloads if speed exceeds (kB/s, 0 = disable)", 
"Automatically expand folders in Queue", 
"Extensions", 
"External / WAN IP", 
"Only show joins / parts for favorite users", 
"Favorite download directories", 
"Favorites", 
"Filename", 
"Maximum simultaneous files (0 = infinite)", 
"Filter kick and NMDC debug messages", 
"Activate search/userlist filter by pressing Enter", 
"Firewall with manual port forwarding", 
"Firewall (passive, worst case)", 
"Firewall with UPnP", 
"Format", 
"General", 
"Get User Country", 
"Accept custom user commands from hub", 
"Change", 
"Ignore private messages from the hub", 
"Ignore private messages from bots", 
"Incoming connection settings (see Help/FAQ if unsure)", 
"Don't delete file lists when exiting", 
"Language file", 
"Limits", 
"Log directory", 
"Log downloads", 
"Log filelist transfers", 
"Log main chat", 
"Log private chat", 
"Log status messages", 
"Log system messages", 
"Log uploads", 
"Logging", 
"Logs", 
"Max compression level", 
"Max hash speed", 
"Max tab rows", 
"Minimize at program startup", 
"Minimize to tray", 
"Mouse Over", 
"Name", 
"Connection settings", 
"Don't send the away message to bots", 
"Normal", 
"timeout", 
"Note; Files appear in the share only after they've been hashed!", 
"Open new window when using /join", 
"Progressbar colors", 
"Options", 
"Outgoing connection settings", 
"Don't allow hub/UPnP to override", 
"Personal Information", 
"Make an annoying sound every time a private message is received", 
"Make an annoying sound when a private message window is opened", 
"PM history", 
"Open new file list windows in the background", 
"Open new private message windows in the background", 
"Open private messages from the hub in their own window", 
"Open private messages from bots in their own window", 
"Open private messages in their own window", 
"Ports", 
"Priority settings - has higher priority than Autopriority", 
"High prio max size", 
"Highest prio max size", 
"Low prio max size", 
"Set lowest prio for newly added files larger than Low prio size", 
"Normal prio max size", 
"Popup box to input password for hubs", 
"Public Hubs list", 
"Public Hubs list URL", 
"Queue", 
"Rename", 
"Note; most of these options require that you restart AirDC++", 
"Reset", 
"Max sources for match queue", 
"Search history", 
"Select color", 
"&Text style", 
"&Window color", 
"Send unknown /commands to the hub", 
"Share hidden files", 
"Total size:", 
"Shared directories", 
"Show InfoTips in lists", 
"Show joins / parts in chat by default", 
"Show progress bars for transfers (uses some CPU)", 
"Show shell menu in finished transfers and Own FileList", 
"Skip zero-byte files", 
"SOCKS5", 
"Socks IP", 
"Port", 
"Use SOCKS5 server to resolve host names", 
"Login", 
"Sort favorite users first", 
"Sounds", 
"Sounds", 
"Note; because of changing download speeds, this is not 100% accurate...", 
"View status messages in main chat", 
"TCP", 
"TLS/TCP", 
"Colors & Fonts", 
"Show timestamps in chat by default", 
"Set timestamps", 
"Toggle window when selecting an active tab", 
"Toolbar", 
"Add -->", 
"Toolbar Images", 
"<-- Remove", 
"UDP Port", 
"Unfinished downloads directory", 
"Line speed (upload)", 
"Sharing", 
"Open an extra slot if speed is below (0 = disable)", 
"Upload slots", 
"Install URL handler on startup (to handle dchub:// links)", 
"Use CTRL for line history", 
"Use old sharing user interface", 
"Use system icons when browsing files (slows browsing down a bit)", 
"Use TLS when remote client supports it (affects both clients and hubs)", 
"Use vertical view by default", 
"User List Colors", 
"User Commands", 
"User Menu Items", 
"Windows", 
"Window options", 
"Write buffer size", 
"Socket read buffer", 
"Socket write buffer", 
"Override system colors", 
"Override system colors", 
"Shared", 
"Shared Files", 
"Display popup in away mode only", 
"Display popup when minimized only", 
"Shutdown computer", 
"Shutdown action", 
"Shutdown sequence deactivated...", 
"Shutdown sequence activated...", 
"Size", 
"Exactly", 
"Min Size", 
"New virtual name matches old name, skipping...", 
"Slot granted", 
"Slots", 
"Slots set", 
"Slow user", 
"Small file size set", 
"Socks server authentication failed (bad login / password?)", 
"The socks server doesn't support login / password authentication", 
"The socks server failed establish a connection", 
"The socks server requires authentication", 
"Failed to set up the socks server for UDP relay (check socks address and port)", 
"Download begins", 
"Download finished", 
"Unhandled Exception", 
"Faker found", 
"Alternate source added", 
"File is corrupted", 
"Typing sound", 
"Upload finished", 
"Remote client does not fully support TTH - cannot download", 
"Source Type", 
"Specify a search string", 
"Specify a server to connect to", 
"Speed", 
"SSL Error", 
"Started", 
"Status", 
"Emulate DC++ in this hub", 
"Stored password sent...", 
"String not found: ", 
"Supports", 
"Suspend", 
"Tabs on top", 
"Tag", 
"File already exists at the target Download location", 
"Target filename too long", 
"Target removed", 
"TiB", 
"Unable to open TCP/TLS port. File transfers will not work correctly until you change settings or turn off any application that might be using the TCP/TLS port", 
"Manual settings of number of segments", 
"Time", 
"Time left", 
"\r\n- %a - Abbreviated weekday name\r\n- %A - Full weekday name\r\n- %b - Abbreviated month name\r\n- %B - Full month name\r\n- %c - Date and time representation appropriate for locale\r\n- %d - Day of month as decimal number (01 – 31)\r\n- %H - Hour in 24-hour format (00 – 23)\r\n- %I - Hour in 12-hour format (01 – 12)\r\n- %j - Day of year as decimal number (001 – 366)\r\n- %m - Month as decimal number (01 – 12)\r\n- %M - Minute as decimal number (00 – 59)\r\n- %p - Current locale's A.M./P.M. indicator for 12-hour clock\r\n- %S - Second as decimal number (00 – 59)\r\n- %U - Week of year as decimal number, with Sunday as first day of week (00 – 53)\r\n- %w - Weekday as decimal number (0 – 6; Sunday is 0)\r\n- %W - Week of year as decimal number, with Monday as first day of week (00 – 53)\r\n- %x - Date representation for current locale\r\n- %X - Time representation for current locale\r\n- %y - Year without century, as decimal number (00 – 99)\r\n- %Y - Year with century, as decimal number\r\n- %z, %Z - Either the time-zone name or time zone abbreviation, depending on registry settings; no characters if time zone is unknown\r\n- %% - Percent sign\r\n\r\nDefault: %H:%M:%S", 
"Timestamps Help", 
"Timestamps disabled", 
"Timestamps enabled", 
"Greater than maximum filelist size (256 MB)", 
"More data was sent than was expected", 
"Total: ", 
"Transferlist double click action", 
"Transferred", 
"Trusted certificates path", 
"Under construction, restart AirDC++ to see effects...", 
"Experimental feature, don't consider AirDC++ secure in any way", 
"A file with the same hash already exists in your share", 
"TTH Inconsistency", 
"TTH Root", 
"Two colors", 
"Type", 
"Place usercommands to submenu", 
"Unable to create thread", 
"Unable to open filelist: ", 
"Unable to rename ", 
"Unable to send file ", 
"Unfinished file not found", 
"Unfinished file too small", 
"Unignore User", 
"Unknown", 
"Unknown command: ", 
"Unknown error: 0x%x", 
"Update check", 
"Upload finished, idle...", 
"Upload starting...", 
"Uploaded %s (%.01f%%) in %s", 
" uploaded to ", 
"Failed to create port mappings. Please set up your NAT yourself.", 
"Failed to get external IP via  UPnP. Please set it yourself.", 
"Failed to remove port mappings", 
"Use Explorer theme in listviews and treeviews", 
"User", 
"Command", 
"Context", 
"Filelist Menu", 
"Hub IP / DNS (empty = all, 'op' = where operator)", 
"Hub Menu", 
"Chat", 
"Send once per nick", 
"Parameters", 
"PM", 
"Text sent to hub", 
"Search Menu", 
"To", 
"Command Type", 
"User Menu", 
"Create / Modify Command", 
"Command Types:\r\nSeparator: Adds a separator to the menu\r\nRaw: Sends raw command to the hub (experts only, end it with '|'!)\r\nChat: Sends command as if you were typing it in the chat\r\nPM: Sends command as if you sent it by pm\r\nContexts determine where the command is shown:\r\nHub Menu: Hub tab (at the bottom of the screen) right-click menu\r\nChat Menu: User right-click menu in chat and PM tab menu\r\nSearch Menu: Search right-click menu\r\nParameters:\r\nName: Name (use '/' to create submenus)\r\nCommand: Command text (may contain parameters)\r\nHub: Hub ip as typed when connecting (empty = all hubs, \"op\" = hubs where you're op)\r\nTo: PM recipient\r\nOnly once: Send only once per user from search frame\r\nIn the parameters, you can use %[xxx] variables and date/time specifiers (%Y, %m, ...). The following are available:\r\n%[myNI]: your own nick\r\n%[userNI]: the users nick (user && search context only)\r\n%[userTAG]: user tag (user && search context only)\r\n%[userDE]: user description (user && search context only)\r\n%[userEM]: user email (user && search context only)\r\n%[userSS]: user shared bytes (exact) (user && search context only)\r\n%[userSSshort]: user shared bytes (formatted) (user && search context only)\r\n%[userI4]: user ip (if supported by hub)\r\n%[fileFN]: filename (search context only)\r\n%[line:reason]: opens up a window asking for \"reason\"", 
"User Description", 
"User offline", 
"Running... (user online)", 
"User went offline", 
"User went online", 
"Info User", 
"Userlist Icons", 
"Userlist double click action", 
"Users", 
"Running... (%d of %d users online)", 
"Version", 
"Video", 
"View as text", 
"Virtual name", 
"Virtual directory name already exists", 
"Name under which the others see the directory", 
"Waiting...", 
"Waiting for %i seconds before searching...", 
"Waiting time", 
"Waiting to retry...", 
"Waiting (User online)", 
"Waiting (%d of %d users online)", 
"What's &this?", 
"Whois ", 
"/winamp - Works with 1.x, 2.x, 5.x (no WinAmp 3 support)\r\n- %[version]	Numerical Version (ex: 2.91)\r\n- %[state]	Playing state (ex: stopped/paused/playing)\r\n- %[title]		Window title from Winamp - if you want to change this for mp3s, Winamp > Pref > Input > MPEG > Title\r\n- %[rawtitle]	Window title from Winamp (if %[title] not working propertly)\r\n- %[percent]	Percentage (ex. 40%)\r\n- %[length]	Length in minutes:seconds (ex: 04:09)\r\n- %[elapsed]	Time elapsed in minutes:seconds (ex. 03:51)\r\n- %[bar]		ASCII progress bar, 10 characters wide no including brackets (ex. [----|-----])\r\n- %[bitrate]	Bitrate (ex. 128kbps)\r\n- %[sample]	Sample frequency (ex. 22kHz)\r\n- %[channels]	Number of channels (ex. stereo / mono)\r\n- %[path]	Playing full Filepath\r\n- %[directory]	Playing DirectoryName\r\n- %[filename]	Playing FileName\r\n- %[parentdir]	Parent Directory name of %[directory]\r\n Empty = Default String -> winamp(%[version]) %[state](%[title]) stats(%[percent] of %[length] %[bar])", 
"Winamp Help", 
"Yes", 
"ZoneAlarm was detected in your computer.  It is frequently responsible for corrupted downloads and is the cause of many \"rollback inconsistency\" errors.  Please uninstall it and use an alternate product.  ", 
"Regexp", 
"Background image", 
"Reconnect disconnected", 
"Tabs", 
"Make tabs bold on status messages in Hubs", 
"Show icons in tabs", 
"Blend tabs instead of using bold font", 
"Tab Colors", 
"Size of string to display in tabs", 
"Select Color", 
"Blending", 
"Active background color", 
"Active text color", 
"Active border color", 
"Inactive background color", 
"Disconnected/Offline PM color", 
"Inactive text color", 
"Inactive border color", 
"Inactive notification color", 
"Ignore private messages", 
"Hide share in this hub", 
"Back", 
"Play", 
"Pause", 
"Next", 
"Stop", 
"Volume up", 
"Volume 50%", 
"Volume down", 
"Media Toolbar\tCtrl+4", 
"Post media spam to main chat", 
"Popup time", 
"Show preview of private message on popup", 
"&Back color", 
"&Msg text", 
"&Title text", 
"Max length", 
"Popup image", 
"/wmp - Works with Windows Media Player 9+\r\n- %[version]	Version of Windows Media Player\r\n- %[fullversion]	Full version of Windows Media Player\r\n- %[status]	Pre-formatted status string from Windows Media Player\r\n- %[title]		Name of the currently playing item\r\n- %[elapsed]	Time elapsed in (HH:)MM:SS\r\n- %[percent]	Time elapsed presented as percentage from total length\r\n- %[bar]		ASCII progress bar, 10 characters wide no including brackets (ex. [----|-----])\r\n- %[length]	Full length of the current item in (HH:)MM:SS\r\n- %[artist]	Name of the artist for the currently playing item\r\n- %[album]	Name of the album the current song is from\r\n- %[genre]	Genre of the current media\r\n- %[bitrate]	Bitrate for the playing media\r\n- %[year]	Year of album publication (no WMP9 support)\r\n- %[size]		Size of the currently playing file\r\n- %[rating]	Users rating, represented with *'s (if available)\r\n\r\nEmpty = Default String -> +me %[title] at %[bitrate] <Windows Media Player %[version]>", 
"Windows Media Player Help", 
"/itunes - For iTunes media spamming\r\n- %[version]	Numerical Version (ex: 7.0.2.16)\r\n- %[album]	Name of the album the current track is from\r\n- %[artist]	Artist of the current track\r\n- %[title]		Name of the currently playing track\r\n- %[genre]	Genre of the currently playing track\r\n- %[elapsed]	Time elapsed in minutes:seconds\r\n- %[percent]	Time elapsed presented as percentage from total length\r\n- %[bar]		ASCII progress bar, 10 characters wide no including brackets (ex. [----|-----])\r\n- %[length]	Total length of the current track\r\n- %[bitrate]	Bitrate for the playing track (kbps)\r\n- %[frequency]	Frequency for the currently playing track (kHz)\r\n- %[year]	Year of publication/recording of the current track\r\n- %[size]		Size of the currently playing file\r\n- %[state]	Current state of iTunes (playing/stopped)\r\n\r\nEmpty = Default String -> +me playing: %[title] at %[bitrate] <iTunes %[version]>", 
"iTunes Help", 
"/mpc - For Media Player Classic media spamming\r\n- %[filename]	Name of the file currently playing\r\n- %[title]		Name of the currently playing item (without file extension)\r\n- %[size]		Size of the file currently playing\r\n- %[state]	Current state of Media Player Classic (playing/paused/stopped)\r\n- %[elapsed]	Time elapsed in minutes:seconds\r\n- %[percent]	Time elapsed presented as percentage from total length\r\n- %[bar]		ASCII progress bar, 10 characters wide no including brackets (ex. [----|-----])\r\n- %[length]	Total length of the current file\r\n\r\nEmpty = Default String -> +me playing: %[title] <Media Player Classic>", 
"Media Player Classic Help", 
"Selected player doesn't support media spams", 
"Start Media Player", 
"Winamp", 
"Refresh", 
"Artist", 
"Title", 
"Length", 
"Path", 
"Browse..", 
"Ignore", 
"Pattern is already in the list", 
"Clear", 
"Use regexp or wildcards", 
"Ignored users", 
"Misc", 
"incoming", 
"outgoing", 
"Begin", 
"End", 
"Use natural sorting", 
"Virus scan after download finished", 
"Update IP on startup", 
"Show Server Commands as status messages", 
"Show Client Commands as status messages", 
"Download Options", 
"Segments", 
"Minimum segment size", 
"Don't share the following files (separate files with '|', wildcards allowed):", 
"Skiplist Share", 
"Grant minislot automatically for the following file extensions: (separate extensions with '|', wildcards allowed)", 
"Minislots", 
"Share Options", 
"Remove file from queue", 
"Highlight", 
"Begins,Contains,Ends,Equals", 
"String to match", 
"Add...", 
"Change...", 
"Highlight settings", 
"Text styles", 
"Match options", 
"Actions", 
"Text to match", 
"OK", 
"Cancel", 
"Match Type", 
"Update", 
"Move Up", 
"Move Down", 
"Background Color", 
"Select Sound File", 
"Display Popup", 
"Play Sound", 
"Flash Window", 
"Use Highlight for Nicklist (Wildcards or $Re: for Regex)", 
"Whole Line", 
"Entire Word", 
"Change Tabcolor", 
"Add to history", 
"Bold", 
"Italic", 
"Underline", 
"Strikeout", 
"Presets", 
"Add all", 
"My nick", 
"My messages", 
"Users", 
"Timestamps", 
"Urls", 
"/me", 
"Status messages", 
"Joins", 
"Parts", 
"Releases", 
"Winamp spam", 
"Kicked users", 
"Hub links", 
"Text Color", 
"Can't add an empty string", 
"Badly formatted regular expression", 
"AirDC++", 
"Flash window on PM", 
"Flash window on PM only if it's from a new user", 
"Flash window on my nick in PM/Hub", 
"Search", 
"Enable Automatic search for specified files / Directories", 
"Automatically search every", 
"Recheck All items after", 
"Value", 
"Action", 
"Line must not be empty", 
"Search by TTH", 
"Pause", 
"AirAppearance", 
"Get IP", 
"Use Highlights", 
"Background color used in file lists to show files that are already shared", 
"Show Progress bars in Queue", 
"Language", 
"Swedish", 
"Finnish", 
"Italian", 
"Hungarian", 
"Romanian", 
"Danish", 
"English", 
"Portuguese", 
"Polish", 
"French", 
"Dutch", 
"Open First X Hubs at Startup", 
"Search by TTH", 
"Paste", 
"Search Sites", 
"Import Theme", 
"Export Theme", 
"Norwegian", 
"Refresh file list", 
"Use Regexp", 
"Add User to Favorites If Download Speed is over", 
"Filename with path", 
"Case sensitive", 
"Invalid RegExp!", 
"Case insensitive RegExp", 
"Match", 
"Raw", 
"Directory already shared", 
"Remove all subdirectories before adding this one", 
"Open log files internally (performance may decrease when opening huge log files)", 
"Open System Log", 
"Name", 
"Use Dupe Color for Text instead of Background", 
"Info", 
"System Log", 
"Open system log", 
"No system log exists", 
"file list partial", 
"Add/Change Autosearch String", 
"Add/Change Preview Command", 
"Popup colors", 
"General text", 
"General chat text", 
"My nick", 
"My own message", 
"Private message", 
"System message", 
"Server message", 
"Timestamp", 
"The style for timestamp", 
"URL", 
"Favorite user", 
"Operator", 
"Other users", 
"Max resize lines", 
"Use Dupe Color in Search", 
"Russian", 
"Trying to Download File already shared! File: ", 
"Client protection", 
"Enable password protection", 
"Please enter password:", 
"Authentification Required To Preform This Action", 
"Unlock", 
"Protect Tray", 
"Note; If you disable password protection your password will be reset!", 
"Readd all Sources", 
"No password was required/provided at login, disconnecting hub. (Setting @ Misc Page)", 
"Automatically disconnect hubs if not registered", 
"The download directory cannot be shared", 
"Bold hub's tabs on kick messages", 
"Skiplist, Wildcards, Separate | ", 
"Presets for Search Skiplist, Separate with | *wildcards allowed", 
"Auto Search", 
"Preset1", 
"Preset2", 
"Preset3", 
"Directory is hidden", 
"Directory not shared", 
"Group", 
"Queue Size", 
"Automatically add download sources from search", 
"Update", 
"No UPnP implementation available", 
"Successfully created port mappings", 
"Update file has finished downloading. Do you Wish to update? (AirDC++ will exit)", 
"Updater File detected. Do you Wish to update? (AirDC++ will exit)", 
"Test Write to AirDC++ folders on startup", 
"Incoming Refresh Time", 
"Use ADLSearch on Filelists", 
"Use ADLSearch on Own FileList", 
"Don't download files already in queue", 
"File with same TTH allready exists in Queue", 
"Show User Joins / Parts", 
"Successfully removed port mappings", 
"Show Finished Uploads in System Log", 
"Show Finished Downloads in System Log", 
"Settings Wizard", 
"Format Release Names as Links in chat", 
"Copy Directory", 
"Search Directory for alternates", 
"calculated CRC32 does not match the one found in SFV file.", 
"Search Directory", 
"Search Google", 
"Search Google (title only)", 
"Search Google (full release name)", 
"Search TV.com", 
"Search Imdb", 
"Search Metacritic", 
"Log Mainchat", 
"Max View History Lines", 
"View Chat History", 
"Could not Move Finished File", 
"Report Hit in Mainchat", 
"German", 
"FILE MISSING: ", 
"Scan share for missing/extra files", 
"Scan folder for missing/extra files", 
"Extra files in Sample folder: ", 
"Extra files in Release folder: ", 
"NFO file possibly missing: ", 
"SFV file possibly missing: ", 
"Multiple NFO files found: ", 
"Multiple SFV files found: ", 
"Scan for missing/extra files started...", 
"Dupe found: ", 
"is the same as", 
"Check missing release files", 
"Check missing SFV files", 
"Check missing NFO files", 
"Check missing SFV or NFO files from music directories (if enabled)", 
"Check extra SFV/NFO files", 
"Check extra files in the release folders", 
"Check duplicate directory names", 
"Scanning options for missing/extra files", 
"Hash Database rebuild Started", 
"Sort Directories First in SearchWindow", 
"Decrease Ram WorkingSet size on minimize", 
"Perform SFV check", 
"Perform SFV check (whole folder)", 
"Perform SFV check (file only)", 
"CRC Mismatch: ", 
"CRC OK: ", 
"files remaining: ", 
"SFV check finished: there were %d files with proper checksum and %d files with invalid checksum (unable to check %d files)", 
"SFV check started, type /stop in chat to stop it", 
"SFV check stopped", 
"Unable to check file: ", 
"No SFV file found", 
"No SFV file found or the selected file isn't listed in it", 
"There are no files in this folder", 
"Failed to open SFV file: ", 
"Open System Log to see the scan results", 
"Stop", 
"Show Notify Icon on chat messages", 
"Use Chat Notify Icon", 
"Find and view NFO", 
"No NFO files found!", 
"Scan in progress", 
"The remote client doesn't support this feature", 
"The remote client is too old, retrying soon with full list...", 
"Download customizations", 
"Guides", 
"/spotify - For Spotify media spamming\r\n- %[title]		Artist and the title of the currently playing item\r\n- %[link]		Spotify link to the track being played\r\n\r\nEmpty = Default String -> /me playing on Spotify: %[title] %[link]", 
"Spotify Help", 
"Play this track on Spotify", 
"View this artist on Spotify", 
"View this album on Spotify", 
"File too big, not shared:", 
"Don't share files bigger than (0=disable)", 
"The directory is empty:", 
"Search File for alternates", 
"NFO/SFV found but there are no other files in the folder:", 
"Check if the folder only contains NFO/SFV file", 
"Check if the directory is empty", 
"Date Modified", 
"Per user limits (only used in ADC hubs)", 
"Max downloads per user", 
"Max uploads per user", 
"Don't share 0 Byte files", 
"Line Speed (download)", 
"Detect automatically", 
"Line Speed", 
"Speed & Limits", 
"Upload Limits (with auto detection)", 
"Upload Limits (manually set)", 
"Download Limits", 
"Settings Profile", 
"Public Hubs (default)", 
"Rar Hubs", 
"Private Hubs", 
"* Lowering the upload connections from the default value will result the download connections to be set to the same value", 
"Use Target Drive for unfinished files", 
"Remove after found", 
"Search Added to Autosearch List: ", 
"Ignore items matching the share skiplist", 
"Ignore zero byte files", 
"No files to download", 
"Matching File lists, this may take a while if the lists are large.", 
"Subtract list: Skip Dirs with ONLY 2 or less files smaller than", 
"Release.Example-AIRDC", 
"Underline links", 
"Underline dupes", 
"Use dupe color in filelists", 
"Use dupe color in chat", 
"Client version", 
"Language version", 
"FileList Highlight", 
"Highlight-AIRDC", 
"HighLight matches in Filelists (wildcards, | separate)", 
"Example, *NORDIC* (this may slow down filelist loading...)", 
"Dupes Settings", 
"Show Skiplist blocked files in systemlog", 
"user(s)", 
"connection(s)", 
"Bundle / Filename", 
"Bundle", 
"bundles", 
"Remove bundle from queue", 
"Bundle removed", 
"Enable partial bundle/file sharing", 
"Show popup on bundle download finished", 
"Show popup on bundle upload finished", 
"Scan finished bundles for missing/extra files", 
"The bundle %s has finished downloading", 
"The bundle %s has finished downloading and will be scanned for missing/extra files", 
"Upload queue", 
"Remove user from this bundle", 
"Bundle Priority", 
"Reload", 
"Dupe share folders/files", 
"Dupe queue folders/files", 
"The share has been scanned for missing/extra files", 
"The selected folders have been scanned for missing/extra files", 
"The bundle %s has finished downloading and has been scanned for missing/extra files", 
"The bundle %s won't be shared because the following problems were found: ", 
"no problems were found", 
"and the following problems were found", 
"%d missing release files", 
"%d missing SFV files", 
"%d missing NFO files", 
"%d folders with extra files", 
"%d empty folders", 
"%d duplicate folders", 
"The selected folder contains %d directory bundles and %d file bundles. Are you sure want to remove them?", 
"Are you sure want to remove the bundle %s?", 
"Are you sure want to remove the directory %s in the bundle %s?", 
"The bundles in the selected directory contain total of %d finished files. Do you also want to remove them?", 
"The selected bundle contains total of %d finished files. Do you also want to remove them?", 
"The selected bundle directory contains total of %d finished files. Do you also want to remove them?", 
"The selected folder contains %d directory bundles and %d file bundles. Are you sure want to move them to %s?", 
"Are you sure want to move the bundle %s to %s?", 
"Are you sure want to move the directory %s in the bundle %s to %s?", 
"The bundles in the selected directory contain total of %d finished files. Do you also want to move them?", 
"The selected bundle contains total of %d finished files. Do you also want to move them?", 
"The selected bundle directory contains total of %d finished files. Do you also want to move them?", 
"ADLSearch", 
"Matching Filelist with ADLSearch, this might take a while if the list is large...", 
"Show Hashing Files in systemlog", 
"The ADLSearch list can't be modified while matching is in progress!", 
"Balanced (change priorities dynamically)", 
"Set priorities automatically based on the progress", 
"Download in the order of adding", 
"Download in random order", 
"Also priorize the order among bundle files", 
"Queue options", 
"Download order", 
"Priorities", 
"Automatically save shares every ", 
"Use external sfv checking (ex. FTPLogger, Enable this only if you know what you are doing)  ", 
"The selected Theme has custom icons, do you wish to load them?\r\n You will need to restart airdc++ for the icons to load.", 
"Restore Default icons?\r\n You will need to restart airdc++ for the icons to load.", 
"Default Icons", 
"Themes: ", 
"AutoSearch", 
"Enable Item(s)", 
"Disable Item(s)", 
"Search bundle for alternatives", 
"Match partial list", 
"Show shared directories in the \"Download to\" menu", 
"There is only %s remaining in the directory %s while %s is needed. Do you want to continue?", 
"Searching the bundle %s for alternatives, %d search(es) queued.", 
"Searching alternates for a RECENT bundle %s, %d search(es) queued.", 
"Next search in %d minutes", 
"Next recent search in %d minutes", 
"The bundle %s has been created with %d items", 
"The bundle %s has been created with %d items (total size: %s) and it has been searched for alternates, %d search(es) queued.", 
"The bundle %s has been created with %d items (%d existing bundles have been merged into it)", 
"%d existing bundles have been merged into it", 
"The file bundle %s has been merged into bundle %s", 
"The file bundle %s has been moved to %s", 
"The bundle %s has been merged into existing bundle %s (%d items were merged)", 
"%d items were added into an existing bundle %s", 
"The file %s has been added into an existing bundle %s", 
"The bundle %s has been moved to %s", 
"The instant sharing feature is disabled, please add the bundle in share manually", 
"The bundle %s isn't in a shared folder, please add it in share manually", 
"Failed to hash the bundle %s, not shared", 
"Failed to add the bundle %s in share", 
"The bundle %s has finished hashing", 
"The bundle %s has finished hashing and it has been added into shared", 
"Seems that you are trying to move all files in the bundle %s. Do you want to move the whole bundle directory instead?", 
"Only from users with nick Matching:  (Wildcards, | separate)", 
"User Match", 
"Use full filelists as last resort if adding sources fails", 
"Matched %d file(s) in the bundle %s, of which %d were new", 
"Matched %d file(s) in %d bundles, of which %d were new", 
"No matching files were found!", 
"Added as source for %d items in the bundle %s", 
"Added as source for %d items in %d bundles", 
"Report added sources in System Log", 
"Set the bundle priority", 
"Set the bundle priorities", 
"Set the file priority", 
"Set the file priorities", 
"A failed bundle %s has been readded in queue", 
"Target file is missing or wrong size", 
"The file matches the download skiplist", 
"Automatically expand bundles in Transferview", 
"Allow fast users to overlap slower ones if there is nothing else to download", 
"Web Shortcuts", 
"Web shortcuts are used to open web pages with specific contents.\nThe key is used in chat / commands Example: /google \"Movie Name\"\nKey can be more than one character, but can not a space.\n\nThe search string added to the end of URL will be picked with rightclick on mouse over from Chat/Search/Filelist windows,\nIf select empty space or no search string is found,\nnothing will be pasted to the url, and the page will just open up.\nAn example: http://domain.com/search=\n\nNote: The key is case sensitive!\n\nClean search term means a title will be attempted to pick from the string. e.g \"Movie.Name.2003.DVDRip.XviD-ABC\" will become \"Movie Name\"", 
"Name Required", 
"Name Already in use", 
"Key Already in use", 
"How To use", 
"Clean search term", 
"WebShortCuts", 
"Country information", 
"Country format", 
"Country Format Help", 
"This box allows customization of the way user country information is displayed throughout the interface. Default: %[2code] - %[name]\r\n\r\n  Available variables: \r\n  %[2code] gets replaced by a 2-letters country code (eg DE, FR). \r\n  %[3code] gets replaced by a 3-letters country code (eg DEU, FRA). \r\n  %[continent] gets replaced by a continent code (AF, AS, EU, NA, OC, SA for Africa, Asia, Europe, North America, Oceania and South America). \r\n  %[engname] gets replaced by the English country friendly name (eg Germany, France). \r\n  %[name] gets replaced by the localized country friendly name (eg Germany, France on an English operating system). \r\n  %[officialname] gets replaced by the localized country official name (eg Federal Republic of Germany, French Republic on an English operating system).", 
"Closing connections", 
"Processing, please wait...", 
"Saving hash data", 
"Saving settings", 
"Saving the share cache", 
"Shutting down.", 
"HTTP Proxy", 
"Download Locations", 
"Segmented Downloads", 
"Automatically search for alternative bundle sources", 
"Searching Options", 
"Search Matching", 
"Skipping options", 
"Download Skiplist (separate files with '|', wildcards allowed)", 
"High priority files (separate files with '|', wildcards allowed)", 
"Use the date of the remote directory for time parameters", 
"And the bundle speed exceeds", 
"And the minimum number of bundle downloads is", 
"Use slow speed disconnecting by default for new bundles", 
"Set highest priority for files matching the high priority list", 
"The maximum age for a bundle dir to consider it as recent", 
"Paths (the one with most disk space will be picked)", 
"Paths", 
};
std::string dcpp::ResourceManager::names[] = {
"AairdcppLanguageFile", 
"AairdcppLanguageVersion", 
"Active", 
"ActiveSearchString", 
"Add", 
"AddAsSource", 
"AddFinishedInstantly", 
"AddToFavorites", 
"AddToQueue", 
"Added", 
"AdlSearch", 
"AdlsDestination", 
"AdlsDiscard", 
"AdlsDownload", 
"AdlsEnabled", 
"AdlsFullPath", 
"AdlsProperties", 
"AdlsSearchString", 
"AdlsSizeMax", 
"AdlsSizeMin", 
"AdlsType", 
"AdlsUnits", 
"All", 
"All3UsersOffline", 
"All4UsersOffline", 
"AllDownloadSlotsTaken", 
"AllFileSlotsTaken", 
"AllUsersOffline", 
"AlternatesSend", 
"AntiPassiveSearch", 
"AllowNatTraversal", 
"Any", 
"AtLeast", 
"AtMost", 
"Audio", 
"Auto", 
"AutoConnect", 
"AutoGrant", 
"Automatic", 
"Average", 
"AverageUpload", 
"Away", 
"AwayModeOff", 
"AwayModeOn", 
"B", 
"BalloonPopups", 
"BitziLookup", 
"BlockFinished", 
"BothUsersOffline", 
"Browse", 
"BrowseAccel", 
"BrowseFileList", 
"Bumped", 
"Cancel", 
"CertificateGenerated", 
"CertificateNotTrusted", 
"CertificateGenerationFailed", 
"Cid", 
"Cipher", 
"Clear", 
"Clientid", 
"Close", 
"CloseConnection", 
"CollapseAll", 
"ColorOp", 
"ColorPasive", 
"CommandTooLong", 
"Comment", 
"Compressed", 
"CompressionError", 
"Configure", 
"ConfiguredHubLists", 
"Connect", 
"ConnectAll", 
"ConnectFavuserHub", 
"Connected", 
"Connecting", 
"ConnectingForced", 
"ConnectingTo", 
"ConnectingToServer", 
"Connection", 
"ConnectionClosed", 
"ConnectionDetection", 
"ConnectionError", 
"ConnectionTimeout", 
"ContinueSearch", 
"Copy", 
"CopyAll", 
"CopyDescription", 
"CopyEmailAddress", 
"CopyExactShare", 
"CopyHub", 
"CopyIp", 
"CopyLine", 
"CopyMagnetLink", 
"CopyNick", 
"CopyNickIp", 
"CopyTag", 
"CopyUrl", 
"Coral", 
"CorruptionDetected", 
"CouldNotOpenTargetFile", 
"Count", 
"Country", 
"CreatingHash", 
"CurrentVersion", 
"CurrentLanguage", 
"DataRetrieved", 
"DecompressionError", 
"Default", 
"Description", 
"Destination", 
"Directory", 
"DirectoryAddError", 
"DisableSounds", 
"Disabled", 
"DisconnectAll", 
"DisconnectUser", 
"Disconnected", 
"DisconnectedUser", 
"Document", 
"Done", 
"DontAddSegmentText", 
"DontRemoveSlashPassword", 
"DontShareTempDirectory", 
"Download", 
"DownloadFailed", 
"DownloadFinishedIdle", 
"DownloadQueue", 
"DownloadStarting", 
"DownloadTo", 
"DownloadWholeDir", 
"DownloadWholeDirTo", 
"DownloadWithPriority", 
"Downloaded", 
"DownloadedBytes", 
"DownloadedFrom", 
"DownloadedParts", 
"Downloading", 
"DownloadingHubList", 
"DownloadingList", 
"DownloadsRunning", 
"DuplicateSource", 
"Eb", 
"EditAccel", 
"Email", 
"EnableMultiSource", 
"EnterNick", 
"EnterPassword", 
"EnterSearchString", 
"ErrorCreatingHashDataFile", 
"ErrorCreatingRegistryKeyAdc", 
"ErrorCreatingRegistryKeyDchub", 
"ErrorCreatingRegistryKeyMagnet", 
"ErrorHashing", 
"ErrorSavingHash", 
"Errors", 
"ExactShared", 
"ExactSize", 
"Executable", 
"ExpandAll", 
"ExpandedResults", 
"ExtraHubSlots", 
"ExtraSlotsSet", 
"FailedToShutdown", 
"FailedToLoadCertificate", 
"FailedToLoadPrivateKey", 
"FavJoinShowingOff", 
"FavJoinShowingOn", 
"FavoriteDirName", 
"FavoriteDirNameLong", 
"FavoriteHubAdded", 
"FavoriteHubAlreadyExists", 
"FavoriteHubDoesNotExist", 
"FavoriteHubIdentity", 
"FavoriteHubProperties", 
"FavoriteHubConnection", 
"FavoriteHubRemoved", 
"FavoriteHubs", 
"FavoriteUserAdded", 
"FavoriteUsers", 
"FavuserOnline", 
"File", 
"FileAlreadyFinished", 
"FileList", 
"FileListDiff", 
"FileListRefreshFailed", 
"FileListRefreshFinished", 
"FileListRefreshInProgress", 
"FileListRefreshInitiated", 
"FileNotAvailable", 
"FileType", 
"FileWithDifferentSize", 
"FileWithDifferentTth", 
"Filename", 
"Files", 
"FilesLeft", 
"FilesPerHour", 
"Filter", 
"Filtered", 
"Find", 
"FinishedDownload", 
"FinishedDownloads", 
"FinishedUpload", 
"FinishedUploads", 
"Folder", 
"Forbidden", 
"ForbiddenDollarFile", 
"ForceAttempt", 
"Gib", 
"GenerateCertificates", 
"GetFileList", 
"GoToDirectory", 
"GrantExtraSlot", 
"GrantExtraSlotDay", 
"GrantExtraSlotHour", 
"GrantExtraSlotWeek", 
"GrantSlotsMenu", 
"GroupSearchResults", 
"HashDatabase", 
"HashProgress", 
"HashProgressBackground", 
"HashProgressStats", 
"HashProgressText", 
"HashReadFailed", 
"HashRebuilt", 
"HashingFailed", 
"HashingFinished", 
"Hibernate", 
"High", 
"Highest", 
"History", 
"HitCount", 
"HitRatio", 
"Hits", 
"Hub", 
"HubAddress", 
"HubConnected", 
"HubDisconnected", 
"HubList", 
"HubListDownloaded", 
"HubListEdit", 
"HubListLoadedFromCache", 
"HubName", 
"HubSegments", 
"HubTopic", 
"HubUsers", 
"HublistCacheCorrupted", 
"HublistDownloadCorrupted", 
"Hubs", 
"Chatdblclickaction", 
"Check0byteShare", 
"CheckForbidden", 
"CheckInflated", 
"ChooseFolder", 
"IgnoreTthSearches", 
"IgnoreUser", 
"IgnoredMessage", 
"IncompleteFavHub", 
"IntegrityCheck", 
"InvalidListname", 
"InvalidNumberOfSlots", 
"InvalidSize", 
"InvalidTargetFile", 
"InvalidTree", 
"Ip", 
"IpBare", 
"Items", 
"JoinShowingOff", 
"JoinShowingOn", 
"Joins", 
"Kib", 
"Kbps", 
"KeepFinishedFiles", 
"KickUser", 
"KickUserFile", 
"LargerTargetFileExists", 
"LastHub", 
"LastChange", 
"LastSeen", 
"LatestVersion", 
"Langdownload", 
"Left", 
"LeftColor", 
"LibCrash", 
"Limit", 
"ListenerFailed", 
"LoadedFileList", 
"Loading", 
"LoadingFileList", 
"Lock", 
"LogOff", 
"Low", 
"Lowest", 
"PreviewName", 
"PreviewApplication", 
"PreviewArguments", 
"PreviewExtension", 
"MagnetAsk", 
"MagnetDlgFile", 
"MagnetDlgHash", 
"MagnetDlgNothing", 
"MagnetDlgQueue", 
"MagnetDlgRemember", 
"MagnetDlgSearch", 
"MagnetDlgSize", 
"MagnetDlgTextBad", 
"MagnetDlgTextGood", 
"MagnetDlgTitle", 
"MagnetHandlerDesc", 
"MagnetHandlerRoot", 
"MagnetShellDesc", 
"ManageGroups", 
"MatchQueue", 
"MaxHubs", 
"MaxSegmentsNumber", 
"MaxSize", 
"MaxUsers", 
"Maxhubs", 
"Maxusers", 
"Mib", 
"Mbitsps", 
"Mbps", 
"MenuAbout", 
"MenuAdlSearch", 
"MenuArrange", 
"MenuCascade", 
"MenuCdmdebugMessages", 
"MenuCloseAllDirList", 
"MenuCloseAllOfflinePm", 
"MenuCloseAllPm", 
"MenuCloseAllSearchframe", 
"MenuCloseDisconnected", 
"MenuDiscuss", 
"MenuDonate", 
"MenuDownloadQueue", 
"MenuExit", 
"MenuFaq", 
"MenuFavoriteHubs", 
"MenuFavoriteUsers", 
"MenuFile", 
"MenuFileRecentHubs", 
"MenuFollowRedirect", 
"MenuHashProgress", 
"MenuHelp", 
"MenuHelpGeoipfile", 
"MenuHelpTranslations", 
"MenuHomepage", 
"MenuHorizontalTile", 
"MenuMinimizeAll", 
"MenuNetworkStatistics", 
"MenuNotepad", 
"MenuOpenDownloadsDir", 
"MenuOpenFileList", 
"MenuOpenMatchAll", 
"MenuOpenOwnList", 
"MenuPublicHubs", 
"MenuQuickConnect", 
"MenuReconnect", 
"MenuRefreshFileList", 
"MenuRestoreAll", 
"MenuSearch", 
"MenuSearchSpy", 
"MenuSettings", 
"MenuShow", 
"MenuStatusBar", 
"MenuToolbar", 
"MenuTransferView", 
"MenuTransfers", 
"MenuTth", 
"MenuVerticalTile", 
"MenuView", 
"MenuWindow", 
"Menubar", 
"MinShare", 
"MinSlots", 
"MinimumSearchInterval", 
"Minshare", 
"Minslots", 
"Minutes", 
"Mode", 
"Move", 
"MoveDown", 
"MoveUp", 
"MynickInChat", 
"NetworkStatistics", 
"New", 
"NewDisconnect", 
"Next", 
"Nick", 
"NickTaken", 
"NickUnknown", 
"No", 
"NoCertificateFileSet", 
"NoDirectorySpecified", 
"NoDownloadsFromSelf", 
"NoErrors", 
"NoFreeBlock", 
"NoFullTree", 
"NoLogForHub", 
"NoLogForUser", 
"NoMatches", 
"NoNeededPart", 
"NoSlotsAvailable", 
"NoUsers", 
"NoUsersToDownloadFrom", 
"None", 
"Normal", 
"NotListening", 
"Notepad", 
"NumberOfSegments", 
"Offline", 
"Ok", 
"Online", 
"OnlyFreeSlots", 
"OnlyTth", 
"OnlyWhereOp", 
"Open", 
"OpenDownloadPage", 
"OpenFolder", 
"OpenHubLog", 
"OpenUserLog", 
"OverlapChunks", 
"OverlappedSlowSegment", 
"OwnCertificateFile", 
"Parts", 
"ParamExists", 
"PassiveUser", 
"Password", 
"Path", 
"PauseSearch", 
"Paused", 
"Pib", 
"Picture", 
"Play", 
"PopupDownloadFailed", 
"PopupDownloadFinished", 
"PopupDownloadStart", 
"PopupFavoriteConnected", 
"PopupHubConnected", 
"PopupHubDisconnected", 
"PopupNewPm", 
"PopupPm", 
"PopupType", 
"PopupBaloon", 
"PopupCustom", 
"PopupSplash", 
"PopupWindow", 
"PopupUploadFinished", 
"Port", 
"PowerOff", 
"PressFollow", 
"PreviewMenu", 
"PreviousFolders", 
"Priority", 
"PrivateKeyFile", 
"PrivateMessage", 
"PrivateMessageFrom", 
"ProgressBack", 
"ProgressCompress", 
"ProgressDone", 
"ProgressDownloaded", 
"ProgressRunning", 
"ProgressSegment", 
"ProgressVerified", 
"ProgressbarOdcStyle", 
"Properties", 
"PublicHubs", 
"Purge", 
"RegexpTester", 
"RegexpMatch", 
"RegexpMismatch", 
"RegexpInvalid", 
"Regexp", 
"Queued", 
"QuickConnect", 
"Rating", 
"Ratio", 
"ReaddSource", 
"ReallyExit", 
"ReallyRemove", 
"Reason", 
"Reboot", 
"RecentHubs", 
"RecheckFile", 
"RedirectAlreadyConnected", 
"RedirectUser", 
"Refresh", 
"RefreshUserList", 
"Reliability", 
"Requesting", 
"RequestingList", 
"Remove", 
"RemoveAll", 
"RemoveExtraSlot", 
"RemoveFromAll", 
"RemoveOffline", 
"RemoveSource", 
"RenamedTo", 
"Report", 
"ReportAlternates", 
"Resume", 
"RetrievingData", 
"RightColor", 
"Running", 
"Search", 
"SearchFor", 
"SearchForAlternates", 
"SearchForFile", 
"SearchInResults", 
"SearchOptions", 
"SearchSpamFrom", 
"SearchSpy", 
"SearchString", 
"SearchingFor", 
"Seconds", 
"SeekBeyondEnd", 
"Segment", 
"Segments", 
"SelectAll", 
"SelectUserList", 
"SendPrivateMessage", 
"SendPublicMessage", 
"Separator", 
"Server", 
"SetczdcBackColor", 
"SetczdcDefaultStyle", 
"SetczdcDisconnectingEnable", 
"SetczdcDownloadSpeed", 
"SetczdcErrorColor", 
"SetczdcIDownSpeed", 
"SetczdcMagnetUriHandler", 
"SetczdcMinFileSize", 
"SetczdcNoteSmallUp", 
"SetczdcPassiveSearch", 
"SetczdcPmLines", 
"SetczdcPreview", 
"SetczdcPrivateSound", 
"SetczdcProgressbarColors", 
"SetczdcProgressbarText", 
"SetczdcRemoveForbidden", 
"SetczdcSlowDisconnect", 
"SetczdcSmallFiles", 
"SetczdcSmallUpSlots", 
"SetczdcStyles", 
"SetczdcTextColor", 
"SetczdcTextStyle", 
"SetczdcTimeDown", 
"SetczdcTo", 
"SetczdcUpload", 
"SetczdcUploadSpeed", 
"SetczdcWinamp", 
"SetczdcWinampPath", 
"SetstrongdcPartialSlots", 
"Settings", 
"SettingsAddFolder", 
"SettingsAdlsBreakOnFirst", 
"SettingsAdvanced", 
"SettingsAdvancedSuppressMainChat", 
"SettingsAdvanced3", 
"SettingsAllowUntrustedClients", 
"SettingsAllowUntrustedHubs", 
"SettingsAntiFrag", 
"SettingsAppearance", 
"SettingsArgument", 
"SettingsAutoAway", 
"SettingsAutoFollow", 
"SettingsAutoKick", 
"SettingsAutoKickNoFavs", 
"SettingsAutoOpen", 
"SettingsAutoPriorityDefault", 
"SettingsAutoRefreshTime", 
"SettingsAutoSearchLimit", 
"SettingsAutoSlots", 
"SettingsAvipreview", 
"SettingsBindAddress", 
"SettingsBindAddressHelp", 
"SettingsBoldOptions", 
"SettingsCertificates", 
"SettingsClearSearch", 
"SettingsColorAlternate", 
"SettingsColorFavorite", 
"SettingsColorIgnored", 
"SettingsColorNormal", 
"SettingsColorReserved", 
"SettingsColors", 
"SettingsCommand", 
"SettingsCompressTransfers", 
"SettingsConfigureHubLists", 
"SettingsConfirmDialogOptions", 
"SettingsConfirmExit", 
"SettingsConfirmHubRemoval", 
"SettingsConfirmItemRemoval", 
"SettingsCzdc", 
"SettingsCzdcExtraDownloads", 
"SettingsDefaultAwayMsg", 
"SettingsDirect", 
"SettingsDirectories", 
"SettingsDisplayDcUpdate", 
"SettingsDontDlAlreadyShared", 
"SettingsDownconn", 
"SettingsDownloadDirectory", 
"SettingsDownloads", 
"SettingsDownloadsMax", 
"SettingsDownloadsSpeedPause", 
"SettingsExpandQueue", 
"SettingsExtensions", 
"SettingsExternalIp", 
"SettingsFavShowJoins", 
"SettingsFavoriteDirs", 
"SettingsFavoriteDirsPage", 
"SettingsFileName", 
"SettingsFilesMax", 
"SettingsFilterMessages", 
"SettingsFilterEnter", 
"SettingsFirewallNat", 
"SettingsFirewallPassive", 
"SettingsFirewallUpnp", 
"SettingsFormat", 
"SettingsGeneral", 
"SettingsGetUserCountry", 
"SettingsHubUserCommands", 
"SettingsChange", 
"SettingsIgnoreHubPms", 
"SettingsIgnoreBotPms", 
"SettingsIncoming", 
"SettingsKeepLists", 
"SettingsLanguageFile", 
"SettingsLimit", 
"SettingsLogDir", 
"SettingsLogDownloads", 
"SettingsLogFilelistTransfers", 
"SettingsLogMainChat", 
"SettingsLogPrivateChat", 
"SettingsLogStatusMessages", 
"SettingsLogSystemMessages", 
"SettingsLogUploads", 
"SettingsLogging", 
"SettingsLogs", 
"SettingsMaxCompress", 
"SettingsMaxHashSpeed", 
"SettingsMaxTabRows", 
"SettingsMinimizeOnStartup", 
"SettingsMinimizeTray", 
"SettingsMouseOver", 
"SettingsName", 
"SettingsNetwork", 
"SettingsNoAwaymsgToBots", 
"SettingsNormal", 
"SettingsOdcShutdowntimeout", 
"SettingsOnlyHashed", 
"SettingsOpenNewWindow", 
"SettingsOperacolors", 
"SettingsOptions", 
"SettingsOutgoing", 
"SettingsOverride", 
"SettingsPersonalInformation", 
"SettingsPmBeep", 
"SettingsPmBeepOpen", 
"SettingsPmHistory", 
"SettingsPopunderFilelist", 
"SettingsPopunderPm", 
"SettingsPopupBotPms", 
"SettingsPopupHubPms", 
"SettingsPopupPms", 
"SettingsPorts", 
"SettingsPrioAutoprio", 
"SettingsPrioHigh", 
"SettingsPrioHighest", 
"SettingsPrioLow", 
"SettingsPrioLowest", 
"SettingsPrioNormal", 
"SettingsPromptPassword", 
"SettingsPublicHubList", 
"SettingsPublicHubListUrl", 
"SettingsQueue", 
"SettingsRenameFolder", 
"SettingsRequiresRestart", 
"SettingsReset", 
"SettingsSbMaxSources", 
"SettingsSearchHistory", 
"SettingsSelectColor", 
"SettingsSelectTextFace", 
"SettingsSelectWindowColor", 
"SettingsSendUnknownCommands", 
"SettingsShareHidden", 
"SettingsShareSize", 
"SettingsSharedDirectories", 
"SettingsShowInfoTips", 
"SettingsShowJoins", 
"SettingsShowProgressBars", 
"SettingsShowShellMenu", 
"SettingsSkipZeroByte", 
"SettingsSocks5", 
"SettingsSocks5Ip", 
"SettingsSocks5Port", 
"SettingsSocks5Resolve", 
"SettingsSocks5Username", 
"SettingsSortFavusersFirst", 
"SettingsSound", 
"SettingsSounds", 
"SettingsSpeedsNotAccurate", 
"SettingsStatusInChat", 
"SettingsTcpPort", 
"SettingsTlsPort", 
"SettingsTextStyles", 
"SettingsTimeStamps", 
"SettingsTimeStampsFormat", 
"SettingsToggleActiveWindow", 
"SettingsToolbar", 
"SettingsToolbarAdd", 
"SettingsToolbarImage", 
"SettingsToolbarRemove", 
"SettingsUdpPort", 
"SettingsUnfinishedDownloadDirectory", 
"SettingsUploadLineSpeed", 
"SettingsSharingpage", 
"SettingsUploadsMinSpeed", 
"SettingsUploadsSlots", 
"SettingsUrlHandler", 
"SettingsUseCtrlForLineHistory", 
"SettingsUseOldSharingUi", 
"SettingsUseSystemIcons", 
"SettingsUseTls", 
"SettingsUseVerticalView", 
"SettingsUserColors", 
"SettingsUserCommands", 
"SettingsUserMenu", 
"SettingsWindows", 
"SettingsWindowsOptions", 
"SettingsWriteBuffer", 
"SettingsSocketInBuffer", 
"SettingsSocketOutBuffer", 
"SettingsZdcProgressOverride", 
"SettingsZdcProgressOverride2", 
"Shared", 
"SharedFiles", 
"ShowPopupAway", 
"ShowPopupMinimized", 
"Shutdown", 
"ShutdownAction", 
"ShutdownOff", 
"ShutdownOn", 
"Size", 
"SizeExact", 
"SizeMin", 
"SkipRename", 
"SlotGranted", 
"Slots", 
"SlotsSet", 
"SlowUser", 
"SmallFileSizeSet", 
"SocksAuthFailed", 
"SocksAuthUnsupported", 
"SocksFailed", 
"SocksNeedsAuth", 
"SocksSetupError", 
"SoundDownloadBegins", 
"SoundDownloadFinished", 
"SoundException", 
"SoundFakerFound", 
"SoundSourceAdded", 
"SoundTthInvalid", 
"SoundTypingNotify", 
"SoundUploadFinished", 
"SourceTooOld", 
"SourceType", 
"SpecifySearchString", 
"SpecifyServer", 
"Speed", 
"SslError", 
"Started", 
"Status", 
"StealthMode", 
"StoredPasswordSent", 
"StringNotFound", 
"Supports", 
"Suspend", 
"TabsOnTop", 
"Tag", 
"TargetFileExists", 
"TargetFilenameTooLong", 
"TargetRemoved", 
"Tib", 
"TcpPortBusy", 
"TextManual", 
"Time", 
"TimeLeft", 
"TimestampHelp", 
"TimestampHelpDesc", 
"TimestampsDisabled", 
"TimestampsEnabled", 
"TooLargeList", 
"TooMuchData", 
"Total", 
"Transferlistdblclickaction", 
"Transferred", 
"TrustedCertificatesPath", 
"CertificatesConstuction", 
"CertificatesExperimental", 
"TthAlreadyShared", 
"TthInconsistency", 
"TthRoot", 
"TwoColors", 
"Type", 
"UcSubmenu", 
"UnableToCreateThread", 
"UnableToOpenFilelist", 
"UnableToRename", 
"UnableToSendFile", 
"UnfinishedFileNotFound", 
"UnfinishedFileTooSmall", 
"UnignoreUser", 
"Unknown", 
"UnknownCommand", 
"UnknownError", 
"UpdateCheck", 
"UploadFinishedIdle", 
"UploadStarting", 
"UploadedBytes", 
"UploadedTo", 
"UpnpFailedToCreateMappings", 
"UpnpFailedToGetExternalIp", 
"UpnpFailedToRemoveMappings", 
"UseExplorerTheme", 
"User", 
"UserCmdCommand", 
"UserCmdContext", 
"UserCmdFilelistMenu", 
"UserCmdHub", 
"UserCmdHubMenu", 
"UserCmdChat", 
"UserCmdOnce", 
"UserCmdParameters", 
"UserCmdPm", 
"UserCmdPreview", 
"UserCmdSearchMenu", 
"UserCmdTo", 
"UserCmdType", 
"UserCmdUserMenu", 
"UserCmdWindow", 
"UserCmdDescription", 
"UserDescription", 
"UserOffline", 
"UserOnline", 
"UserWentOffline", 
"UserWentOnline", 
"Userinfo", 
"UserlistIcons", 
"Userlistdblclickaction", 
"Users", 
"UsersOnline", 
"Version", 
"Video", 
"ViewAsText", 
"VirtualName", 
"VirtualNameExists", 
"VirtualNameLong", 
"Waiting", 
"WaitingFor", 
"WaitingTime", 
"WaitingToRetry", 
"WaitingUserOnline", 
"WaitingUsersOnline", 
"WhatsThis", 
"WhoIs", 
"WinampHelp", 
"WinampHelpDesc", 
"Yes", 
"ZonealarmWarning", 
"AdlsRegexp", 
"BackgroundImage", 
"MenuReconnectDisconnected", 
"SettingsAirTabspage", 
"HubBoldTabs", 
"TabShowIcons", 
"BlendTabs", 
"SettingsSbTabColors", 
"SettingsSbTabSize", 
"SettingsBtnColor", 
"SettingsSbDirtyBlend", 
"TabActiveBg", 
"TabActiveText", 
"TabActiveBorder", 
"TabInactiveBg", 
"TabInactiveBgDisconnected", 
"TabInactiveText", 
"TabInactiveBorder", 
"TabInactiveBgNotify", 
"FavNoPm", 
"HideShare", 
"WinampBack", 
"WinampPlay", 
"WinampPause", 
"WinampNext", 
"WinampStop", 
"WinampVolUp", 
"WinampVolHalf", 
"WinampVolDown", 
"ToggleToolbar", 
"WinampSpam", 
"PopupTime", 
"PmPreview", 
"PopupBackColor", 
"PopupFont", 
"PopupTitleFont", 
"MaxMsgLength", 
"PopupImage", 
"WmpHelp", 
"WmpHelpDesc", 
"ItunesHelp", 
"ItunesHelpDesc", 
"MpcHelp", 
"MpcHelpDesc", 
"NoMediaSpam", 
"WinampStart", 
"WinampMenu", 
"WinampRefresh", 
"WinampArtist", 
"WinampTitle", 
"WinampLength", 
"WinampLocation", 
"Browsew", 
"SettingsIgnore", 
"AlreadyIgnored", 
"IgnoreClear", 
"UseRegexpOrWc", 
"IgnoredUsers", 
"SettingsAirdcpage", 
"Incoming", 
"Outgoing", 
"Begin", 
"End", 
"NatSort", 
"SetairdcAntiVir", 
"UpdateIp", 
"SettingsServerCommands", 
"SetClientCommands", 
"SettingsAirdownloads", 
"SettingsAirdownloadsSegment", 
"SettingsAirdownloadsSegmentSize", 
"StSkiplistShare", 
"StSkiplistShareBorder", 
"StMinislotsExt", 
"SbMinislots", 
"SettingsAirsharing", 
"RemoveFile", 
"SettingsAirHighlightpage", 
"HighlightMatchTypes", 
"HighlightlistHeader", 
"HighlightAdd", 
"HighlightChange", 
"HighlightDialogTitle", 
"HighlightTextStyles", 
"HighlightMatchOptions", 
"HighlightActions", 
"HighlightTextToMatch", 
"HighlightOk", 
"HighlightCancel", 
"SettingsStMatchType", 
"SettingsBtnUpdate", 
"SettingsBtnMoveup", 
"SettingsBtnMovedown", 
"SettingsBtnBgcolor", 
"SettingsSelectSound", 
"SettingsPopup", 
"SettingsPlaySound", 
"SettingsFlashWindow", 
"SettingsIncludeNicklist", 
"SettingsWholeLine", 
"SettingsEntireWord", 
"SettingsTabColor", 
"SettingsLastlog", 
"Bold", 
"Italic", 
"Underline", 
"Strikeout", 
"Preset", 
"PresetAddAll", 
"PresetMyNick", 
"PresetMyMessages", 
"PresetUsers", 
"PresetTimestamp", 
"PresetUrls", 
"PresetMe", 
"PresetStatus", 
"PresetJoins", 
"PresetParts", 
"PresetReleases", 
"PresetWinampSpam", 
"PresetKickedUsers", 
"PresetDchub", 
"SettingsBtnTextcolor", 
"AddEmpty", 
"BadRegexp", 
"Airdc", 
"FlashWindowOnPm", 
"FlashWindowOnNewPm", 
"FlashWindowOnMynick", 
"SettingsAirsearch", 
"AutosearchEnable", 
"AutosearchEnableTime", 
"AutosearchRecheckText", 
"SettingsValue", 
"Action", 
"LineEmpty", 
"SearchTth", 
"Pause", 
"SettingsAirappearancepage", 
"GetIp", 
"UseHighlight", 
"SettingsDupeDescription", 
"SettingsShowQueueBars", 
"SettingsLanguage", 
"SettingsLswe", 
"SettingsLfin", 
"SettingsLita", 
"SettingsLhun", 
"SettingsLro", 
"SettingsLdan", 
"SettingsLeng", 
"SettingsLpor", 
"SettingsLpol", 
"SettingsLfr", 
"SettingsLd", 
"OpenFirst", 
"SearchByTth", 
"Paste", 
"SearchSites", 
"ImportTheme", 
"ExportTheme", 
"SettingsLnor", 
"RefreshFileList", 
"UseRegexp", 
"FavDlSpeed", 
"Filewdir", 
"CaseSensitive", 
"InvalidRegexp", 
"CaseInsensitiveRegexp", 
"Match", 
"Raw", 
"DirectoryShared", 
"DirectoryParent", 
"OpenLogsInternal", 
"MenuOpenSystemlog", 
"Name", 
"SettingsDupeText", 
"Info", 
"SystemLog", 
"OpenSystemLog", 
"NoSystemLog", 
"FileListPartial", 
"AutosearchDlg", 
"PreviewDlg", 
"PopupColors", 
"ProppageGeneralText", 
"ProppageGeneralChatText", 
"ProppageMyNick", 
"ProppageMyOwnMsg", 
"ProppagePrivateMsg", 
"ProppageSystemMsg", 
"ProppageServerMsg", 
"ProppageTimestamp", 
"ProppageStyleTimestamp", 
"ProppageUrl", 
"ProppageFavUser", 
"ProppageOperator", 
"ProppageNorm", 
"MaxResizeLines", 
"SettingsDupeSearch", 
"SettingsLrus", 
"FileAlreadyShared", 
"PasswdProtectStatic", 
"PasswdProtectChckbox", 
"PasswordDesc", 
"PasswordTitle", 
"Unlock", 
"PasswdProtectTrayChckbox", 
"Note", 
"ReaddAll", 
"HubNotProtected", 
"DisallowConnectionToPassedHubs", 
"DontShareDownloadDirectory", 
"BoldHubTabsOnKick", 
"Skiplist", 
"SettingsSearhSkiplistPreset", 
"SettingsAsearch", 
"Preset1", 
"Preset2", 
"Preset3", 
"DirectoryIsHidden", 
"DirectoryNotFound", 
"Group", 
"QueueSize", 
"AutoAddSource", 
"Update", 
"UpnpNoImplementation", 
"UpnpSuccessfullyCreatedMappings", 
"UpdateClient", 
"UpdateFileDetected", 
"TestWrite", 
"SettingsIncomingRefreshTime", 
"SettingsUseAdls", 
"SettingsUseAdlsOwnList", 
"SettingDontDlAlreadyQueued", 
"FileWithSameTth", 
"FavShowJoin", 
"UpnpRemovedMappings", 
"SystemShowFinishedUploads", 
"SystemShowFinishedDownloads", 
"Wizard", 
"FormatRelease", 
"CopyDirectory", 
"SearchForAlternatesDir", 
"ErrorHashingCrc32", 
"SearchDirectory", 
"SearchGoogle", 
"SearchGoogleTitle", 
"SearchGoogleFull", 
"SearchTvcom", 
"SearchImdb", 
"SearchMetacritic", 
"FavLogChat", 
"MaxLogLines", 
"ViewHistory", 
"UnableToMove", 
"AsReport", 
"SettingsLger", 
"FileMissing", 
"MenuScanMissing", 
"ScanFolderMissing", 
"ExtraFilesSampledir", 
"ExtraFilesRlsdir", 
"NfoMissing", 
"SfvMissing", 
"MultipleNfo", 
"MultipleSfv", 
"ScanStarted", 
"DupeFound", 
"DupeIsSame", 
"CheckMissing", 
"CheckSfv", 
"CheckNfo", 
"CheckMp3Dir", 
"CheckExtraSfvNfo", 
"CheckExtraFiles", 
"CheckDupes", 
"SettingsScanOptions", 
"RebuildStarted", 
"SortDirs", 
"DecreaseRam", 
"RunSfvCheck", 
"SfvCheckFolder", 
"SfvCheckFile", 
"CrcFailed", 
"CrcOk", 
"CrcRemaining", 
"CrcFinished", 
"CrcStarted", 
"CrcStopped", 
"CrcFileError", 
"NoSfvFile", 
"NoCrc32", 
"NoFilesInFolder", 
"CantOpenSfv", 
"SeeSyslogForResults", 
"Stop", 
"ChatNotify", 
"Notify", 
"ViewNfo", 
"NoNfoFound", 
"ScanRunning", 
"NoPartialSupport", 
"NoPartialSupportRetry", 
"MenuCustomize", 
"MenuGuides", 
"SpotifyHelp", 
"SpotifyHelpDesc", 
"SpotifyTrack", 
"SpotifyArtist", 
"SpotifyAlbum", 
"BigFileNotShared", 
"DontShareBiggerThan", 
"DirEmpty", 
"SearchForAlternatesFile", 
"ReleaseFilesMissing", 
"CheckEmptyReleases", 
"CheckEmptyDirs", 
"Date", 
"SettingsMcnslots", 
"SettingsMaxMcnDl", 
"SettingsMaxMcnUl", 
"SettingsNoZeroByte", 
"SettingsDownloadLineSpeed", 
"Autodetect", 
"LineSpeed", 
"SettingsSpeedLimits", 
"UploadLimits", 
"UploadLimitsAdd", 
"DownloadLimits", 
"SettingsProfile", 
"ProfilePublic", 
"ProfileRar", 
"ProfilePrivate", 
"SettingsMcnNote", 
"SettingsUseTargetdrive", 
"RemoveOnHit", 
"SearchAdded", 
"CheckUseSkiplist", 
"CheckIgnoreZeroByte", 
"NoFilesAvailable", 
"MatchingFileList", 
"SkipSubtractText", 
"ProppageDupeMsg", 
"ProppageUnderlineLinks", 
"ProppageUnderlineDupes", 
"SettingsDupeFilelist", 
"SettingsDupeChat", 
"ClientVersion", 
"LanguageVersion", 
"ProppageListHl", 
"ProppageListHlMsg", 
"ListHlText", 
"ListHlExample", 
"SettingsDupes", 
"ReportSkiplist", 
"NumberOfUsers", 
"NumberOfConnections", 
"BundleFilename", 
"Bundle", 
"Bundles", 
"RemoveBundle", 
"BundleRemoved", 
"PartialSharing", 
"SettingsBundleDlPopup", 
"SettingsBundleUlPopup", 
"SettingsScanFinishedBundles", 
"DlBundleFinished", 
"DlBundleFinishedScan", 
"UploadQueue", 
"RemoveBundleSource", 
"BundlePriority", 
"Reload", 
"ProppageShareDupeText", 
"ProppageQueueDupeText", 
"ScanShareFinished", 
"ScanFolderFinished", 
"ScanBundleFinished", 
"ScanFailedBundleFinished", 
"ScanNoProblems", 
"ScanProblemsFound", 
"XMissingReleaseFiles", 
"XMissingSfvFiles", 
"XMissingNfoFiles", 
"XFoldersExtras", 
"XEmptyFolders", 
"XDupeFolders", 
"ConfirmRemoveDirMultiple", 
"ConfirmRemoveDirBundle", 
"ConfirmRemoveDirBundlePart", 
"ConfirmRemoveDirFinishedMultiple", 
"ConfirmRemoveDirFinishedBundle", 
"ConfirmRemoveDirFinishedBundlePart", 
"ConfirmMoveDirMultiple", 
"ConfirmMoveDirBundle", 
"ConfirmMoveDirBundlePart", 
"ConfirmMoveDirFinishedMultiple", 
"ConfirmMoveDirFinishedBundle", 
"ConfirmMoveDirFinishedBundlePart", 
"MatchAdl", 
"MatchingAdl", 
"LogHashing", 
"AdlsearchInProgress", 
"PriopageOrderBalanced", 
"PriopageOrderProgress", 
"PriopageOrderAdded", 
"PriopageOrderRandom", 
"PriopageBalanceQis", 
"QueueOptions", 
"DownloadOrder", 
"Priorities", 
"SaveShare", 
"UseFtpLogger", 
"IconsInTheme", 
"IconsRestore", 
"IconsDefault", 
"ThemeText", 
"Autosearch", 
"EnableAutosearch", 
"DisableAutosearch", 
"SearchBundleAlt", 
"MatchPartial", 
"FavdirsShowShared", 
"ConfirmSizeWarning", 
"BundleAltSearch", 
"BundleAltSearchRecent", 
"NextSearchIn", 
"NextRecentSearchIn", 
"BundleCreated", 
"BundleCreatedAlt", 
"BundleCreatedMerge", 
"ExistingBundlesMerged", 
"FilebundleMerged", 
"FilebundleMoved", 
"BundleMerged", 
"XBundleItemsAdded", 
"BundleItemAdded", 
"BundleMoved", 
"InstantSharingDisabled", 
"NotInSharedDir", 
"BundleHashFailed", 
"BundleSharingFailed", 
"BundleHashed", 
"BundleShared", 
"ConfirmMoveDirAllFiles", 
"AsUserMatch", 
"UserMatch", 
"SettingsAllowMatchFullList", 
"MatchedFilesBundle", 
"MatchedFilesXBundles", 
"NoMatchedFiles", 
"MatchSourceAdded", 
"MatchSourceAddedXBundles", 
"SettingsReportAddedSources", 
"SetBundlePriority", 
"SetBundlePriorities", 
"SetFilePriority", 
"SetFilePriorities", 
"BundleReadded", 
"TargetFileMissing", 
"DownloadSkiplistMatch", 
"SettingsExpandBundles", 
"SettingsOverlapSlowSources", 
"SettingsSbWebShortcuts", 
"SettingsWsDescr", 
"NameRequired", 
"NameInUse", 
"KeyInUse", 
"SettingsWsHowto", 
"SettingsWsClean", 
"Webshortcuts", 
"CountryInformation", 
"SettingsCountryFormat", 
"SettingsCountryFormatHelpDesc", 
"SettingsCountryFormatHelp", 
"ClosingConnections", 
"Processing", 
"SavingHashData", 
"SavingSettings", 
"SavingShare", 
"ShuttingDown", 
"SettingsHttpProxy", 
"SettingsDownloadLocations", 
"SettingsSegmentedDownloads", 
"SettingsAutoBundleSearch", 
"SettingsSearchingOptions", 
"SettingsSearchMatching", 
"SettingsSkippingOptions", 
"SettingsSkiplistDownload", 
"SettingsHighPrioFiles", 
"SettingsFormatRemoteTime", 
"DisconnectBundleSpeed", 
"DisconnectRunningDownloads", 
"SettingsAutoDropSlowSources", 
"SettingsUseHighestList", 
"SettingsRecentHours", 
"PathsFavdirs", 
"Paths", 
};
